let manga_info = [
  {
    "tipo" : "manga",
    "nome" : "Atsumori-kun no Oyome-san",
    "num_capitulo" : "70",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2018",
    "genero" : "Comedia Drama Romance Shoujo Slice-of-Life",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!)",
    "num_capitulo" : "62",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2022",
    "genero" : "Acao Aventura Comedia Demonios Drama Familia Magia Manhwa Reencarnação Romance Shoujo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "My Childhood Friend Became an Obsessive Male Lead",
    "num_capitulo" : "46",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Drama Fantasia Josei Romance",
  },
  {
    "tipo" : "manhwa",
    "nome" : "A Proprietária Bebê Está se Aposentando",
    "num_capitulo" : "120",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Fantasia Romance Shoujo",
  },
  {
    "tipo" : "manga",
    "nome" : "Isekai De Tochi O Katte Noujou O Tsukurou",
    "num_capitulo" : "31",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2019",
    "genero" : "Ação Aventura Comédia Ecchi Fantasia Harem Romance Shounen",
  },
  {
    "tipo" : "manga",
    "nome" : "Kekkon Yubiwa Monogatari",
    "num_capitulo" : "62",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2016",
    "genero" : "Ação Ecchi Fantasia Harem Magia Romance Seinen",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago",
    "num_capitulo" : "23",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Drama Fantasia Romance Shounen Sobrenatural",
  },
  {
    "tipo" : "manga",
    "nome" : "Fuufu Ijou, Koibito Miman",
    "num_capitulo" : "65",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2020",
    "genero" : "Comédia Drama Escolar Romance Slice-of-Life",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Pretendente Surpresa",
    "num_capitulo" : "124",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2020",
    "genero" : "Comédia Drama Josei Romance Slice-of-Life",
  },
  {
    "tipo" : "manhua",
    "nome" : "I’m Not a Demon",
    "num_capitulo" : "19",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Ação Aventura Drama Fantasia Shounen",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Quando a Filha Ilegítima do Conde se Casa",
    "num_capitulo" : "79",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Comédia Drama Josei Romance Slice-of-Life",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Adelaide",
    "num_capitulo" : "85",
    "text_cap" : "Capitulos:",
    "estado" : "Finalizado",
    "lancamento" : "2023",
    "genero" : "Fantasia Histórico Isekai Romance",
  },
  {
    "tipo" : "manhwa",
    "nome" : "I Confessed to the Boss",
    "num_capitulo" : "59",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2021",
    "genero" : "Comedia Drama Josei Romance Shoujo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "A protagonista feminina está tentando me tornar sua madrasta",
    "num_capitulo" : "41",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2021",
    "genero" : "Fantasia Histórico Josei Romance Shoujo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "A 99° Noiva do Duque",
    "num_capitulo" : "53",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Drama Historico Romance Shoujo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Estou Tentando Me Divorciar do Meu Esposo Vilão, Mas Teremos Um Filho",
    "num_capitulo" : "85",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Drama Fantasia Historico Isekai Josei Manhwa Romance Shoujo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "A Relação Simbiótica Entre uma Coelha e Uma Pantera Negra",
    "num_capitulo" : "125",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2021",
    "genero" : "Aventura Comédia Drama Fantasia Romance Shoujo Sobrenatural",
  },
  {
    "tipo" : "manga",
    "nome" : "I Time-Traveled and Confessed to My Teacher Crush",
    "num_capitulo" : "55",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Slice-of-life Romance Comédia Vida-escolar Viagem-no-tempo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Eu Domei o Protagonista Masculino Que Tentou me Matar",
    "num_capitulo" : "25",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Drama Fantasia Romance Shoujo",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Salvos Uma evolução de monstro LitRPG",
    "num_capitulo" : "35",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Acao Aventura Comedia Drama Fantasia Jogo Shounen",
  },
  {
    "tipo" : "manhwa",
    "nome" : "De Tantas Coisas, Me Tornei um Corvo",
    "num_capitulo" : "87",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Fantasia Romance Shoujo Sobrenatural",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Eu tive um filho do tirano",
    "num_capitulo" : "105",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2023",
    "genero" : "Drama fantasia Josei Romance",
  },
  {
    "tipo" : "manhwa",
    "nome" : "Knight of the Frozen Flower",
    "num_capitulo" : "52",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Ação Aventura Drama Fantasia Histórico Psicológico Romance Shoujo",
  },
  {
    "tipo" : "manga",
    "nome" : "Musume ja Nakute Mama ga Suki nano",
    "num_capitulo" : "30",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2020",
    "genero" : "Comedia Romance Slice-of-Life",
  },
  {
    "tipo" : "manga",
    "nome" : "Saint Seiya Meiou Iden Dark Wing",
    "num_capitulo" : "29",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2020",
    "genero" : "Acao Aventura Fantasia Shounen Sobrenatural",
  },
  {
    "tipo" : "manhua",
    "nome" : "Congelamento Global",
    "num_capitulo" : "7",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Acao Aventura Romance Sobrevivencia",
  },
  {
    "tipo" : "manga",
    "nome" : "Eternamente Level 1 Até A Morte",
    "num_capitulo" : "30",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2021",
    "genero" : "Acao Aventura Fantasia Harem Romance Isekai Magia",
  },
  {
    "tipo" : "manga",
    "nome" : "Mushoku no Eiyuu: Betsu ni Skill Nanka Iranakattan daga",
    "num_capitulo" : "19",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2018",
    "genero" : "Acao Aventura Comédia Fantasia Shounen",
  },
  {
    "tipo" : "manga",
    "nome" : "Shinigami ni Sodaterareta Shoujo wa Shikkoku no Tsurugi wo Mune ni Idaku",
    "num_capitulo" : "17",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2019",
    "genero" : "Acao Aventura Fantasia Misterio Romance Seinen Sobrenatural",
  },
  {
    "tipo" : "manga",
    "nome" : "Tanbo de Hirotta Onna Kishi, Inaka de Ore no Yome dato Omowareteiru",
    "num_capitulo" : "10",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Fantasia Romance Shounen Slice-of-Life",
  },
  {
    "tipo" : "manga",
    "nome" : "Bannou “Murazukuri” Cheat de Otegaru Slow Life ~Mura desu ga Nani ka?~",
    "num_capitulo" : "5",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Acao Aventura Comedia Fantasia Romance Shounen",
  },
  {
    "tipo" : "manga",
    "nome" : "Nihon e Youkoso elf-san",
    "num_capitulo" : "40",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2018",
    "genero" : "Comedia Drama Escolar Romance Slice-of-Life",
  },
  {
    "tipo" : "manga",
    "nome" : "Isekai Kenkokuki",
    "num_capitulo" : "61",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2017",
    "genero" : "Acao Drama Fantasia Harem Isekai Romance Slice-of-Life",
  },
  {
    "tipo" : "manga",
    "nome" : "Isekai Cheat Magician",
    "num_capitulo" : "15",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2017",
    "genero" : "Aventura Fantasia Isekai Romance Acao",
  }
];



