let mangas_e_manhwas = [
    {
        "key": "of",
        "id": "F",
        "nome": "Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!)",
        "text_cap": "Capitulos: ",
        "lancamento": "2022",
        "tipo": "manhwa",
        "num_capitulos": 106,
        "estado": "completo",
        "genero": "Fantasia, Histórico, Josei, Romance, Shoujo, Sobrenatural",
        "pasta": "Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!)",
        "caminho-img": "./imgs/Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!).jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "H",
        "nome": "Hougong Tai Duo, Zhihao Feishengle - My Harem, Grew So Large, I Was Forced to Ascend",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Artes Marciais Aventura, Fantasia, Harem, Isekai Romance, Webtoon acao",
        "pasta": "",
        "caminho-img": "./imgs/Hougong Tai Duo, Zhihao Feishengle - My Harem, Grew So Large, I Was Forced to Ascend.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 3.5,
        "id": "I",
        "nome": "Isekai Cheat Magician",
        "tipo": "manga",
        "num_capitulos": 15,
        "lancamento": "2017",
        "Postado": "2023-02-25",
        "autor": "Takeru Uchida",
        "artista": "Nardack",
        "nomes_alternativos": "Isekai Cheat Majutsushi, 異世界チート魔術師",
        "estado": "ativo",
        "genero": "Aventura, Ação, Fantasia, Isekai Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I/Isekai%20Cheat%20Magician/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Isekai%20Cheat%20Magician.jpg",
        "novo_capitulo": "",
        "historia": "Dois alunos normais do ensino médio, Taichi e Rin, desaparecem em um feixe de luz. Quando perceberam, eles já estavam em um mundo de espadas e magia. Finalmente, depois de experimentar um ataque de monstros, e seguindo a sugestão de aventureiros, eles seguiram o caminho para entrar em uma guilda. Nessa guilda, os dois descobrem que possuem magia, incrivelmente poderosa. Assim, os alunos regulares do ensino médio transformaram-se nos cheaters mais fortes.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "I",
        "nome": "It's Time to Change the Genre",
        "tipo": "manhwa",
        "num_capitulos": 5,
        "lancamento": 2023,
        "Postado": "2023-02-22",
        "autor": "Garin",
        "artista": "Ken",
        "nomes_alternativos": "It’s Time to Change the Genre, I Will Make an Attempt to Change the Genre, I Will Make an Effort to Change the Genre, 장르를 바꿔보도록 하겠습니다",
        "estado": "ativo",
        "genero": "Fantasia, Isekai, Reencarnação,, Romance, Shoujo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/It%E2%80%99s%20Time%20to%20Change%20the%20Genre/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Jangleuleul%20Bakkwobodolog%20Hagessseubnida%20-%20It's%20Time%20to%20Change%20the%20Genre.jpg",
        "novo_capitulo": "",
        "historia": 'Entrei no mundo do meu romance, e gênero favorito através do corpo de outra pessoa.Claro, de todos os personagens, eu só tinha que entrar no corpo da tia do protagonista, a mulher que abusou do sobrinho, a vilã egoísta. De acordo com a história original, em qualquer caso, esperava-se que meu sobrinho deixasse meu lado em breve. A compaixão por ele cresceu, então coloquei meu esforço mais sincero em cuidar dele até o dia em que nos separamos- “Sei que é rude perguntar, já que você tem cuidado de Luca até agora, mas posso levar Luca para Winterwald comigo?” Não tem como isso não acontecer! Quer dizer, acho que poderia ter corrido para mandá-lo embora e viver confortavelmente, mas, inesperadamente meu sobrinho passou os braços em volta da minha cintura e gritou. “M-mãe!” Como me tornei sua mãe de repente?',
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "R",
        "nome": "Rebirth of the Divine Doctor",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "estado": "ativo",
        "genero": "acao Artes Marciais Aventura, Comédia, Fantasia, Histórico Isekai Manhua Medicina Reencarnação,",
        "pasta": "",
        "caminho-img": "./imgs/Rebirth of the Divine Doctor.jpg",
        "novo_capitulo": "",
    },

    {
        "key": "of",
        "id": "T",
        "nome": "Taming the Lady",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "acao Fantasia, Isekai Manhwa Shoujo, Webtoon",
        "pasta": "",
        "caminho-img": "./imgs/Taming the Lady.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "The Lady Wants to Rest",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Isekai Manhwa Romance, Shoujo, Webtoon",
        "pasta": "",
        "caminho-img": "./imgs/The Lady Wants to Rest.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "W",
        "nome": "Wo Shi Yì Shijie Zui Qiang Lingzhu - I Am the Strongest Lord in Another World",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Wo Shi Yì Shijie Zui Qiang Lingzhu - I Am the Strongest Lord in Another World.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bokutachi wa Hanshoku wo Yameta",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Bokutachi wa Hanshoku wo Yameta.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "Tensei shitara Slime Datta Ken Mamono no Kuni no Arukikata",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Tensei shitara Slime Datta Ken Mamono no Kuni no Arukikata.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "Tensei Shitara Ore ga Heroine de Aitsu ga Yuusha Datta",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Tensei Shitara Ore ga Heroine de Aitsu ga Yuusha Datta.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Sensei Wa Koi Wo Oshie Rarenai",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Sensei Wa Koi Wo Oshie Rarenai.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "L",
        "nome": "Lv2 kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life",
        "tipo": "manga",
        "num_capitulos": 50,
        "lancamento": "2019",
        "Postado": "2022-02-26",
        "autor": "KINOJO Miya",
        "artista": "ITOMACHI Akine",
        "nomes_alternativos": "Candidate was a Cheat from Lv2, Chillin Different World Life of the Ex-Brave Candidate was Cheat from Lv2, LV2からチートだった元勇者候補のまったり異世界ライフ",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comedia, Fantasia, Romance, Shounen, slice of life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/L/Lv2%20kara%20Cheat%20datta%20Motoyuusha%20Kouho%20no%20Mattari%20Isekai%20Life/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Lv2 kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life.jpg",
        "novo_capitulo": "",
        "historia": "Um protagonista renascido em outro mundo. Aparentemente ele havia reencarnado como um filho abandonado, junto a outros órfãos. Para sobreviver, ele os conduziu à agricultura. Pouco a pouco, os órfãos se reuniram, e ao ouvir rumores de uma aldeia, outros começaram a migrar. O grupo que tinha sido nada além de crianças tornou-se uma aldeia antes que alguém percebesse. E então, vários países nos arredores começaram a observá-lo... Este é o conto épico do homem que mais tarde seria conhecido como o Imperador Divino.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "I",
        "nome": "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken",
        "tipo": "manga",
        "num_capitulos": 14,
        "lancamento": 2019,
        "Postado": "2024-02-26",
        "autor": "Saeki-san",
        "artista": "KAZUTAKE Hazano",
        "nomes_alternativos": "The Angel Next Door Spoils Me Rotten, お隣の天使様にいつの間にか駄目人間にされていた件",
        "estado": "ativo",
        "genero": "Comedia, Romance, Shounen, fantasia",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/O/Otonari%20no%20Tenshi-sama%20ni%20Itsunomanika%20Dame%20Ningen%20ni%20Sareteita%20Ken/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Otonari%20no%20Tenshi-sama%20ni%20Itsunomanika%20Dame%20Ningen%20ni%20Sareteita%20Ken.jpg",
        "novo_capitulo": "",
        "historia": "Amane mora sozinho em um apartamento, e a garota mais bonita da escola, Mahiru, mora bem ao lado. Eles quase nunca se falam – até o dia em que ele a vê em apuros em um dia chuvoso e empresta seu guarda-chuva a ela. Para retribuir o favor, ela oferece a ele ajuda na casa, e um relacionamento começa a florescer lentamente à medida que a distância entre eles diminui…",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "K",
        "nome": "Kuro no Shoukanshi",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Kuro no Shoukanshi.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "L",
        "nome": "Love Comedy Manga ni Haitteshimatta node, Oshi no Make Heroine wo Zenryoku de Shiawase ni Suru",
        "tipo": "manga",
        "num_capitulos": 2,
        "lancamento": 2022,
        "Postado": "2023-02-05",
        "autor": "Shiryu",
        "artista": "Bara & Shiharu",
        "nomes_alternativos": "Rabukome Manga ni Haitte Shimatta no de, Oshi no Make Heroine wo Zenryoku de Shiawase ni suru, ラブコメ漫画に入ってしまったので、推しの負けヒロインを全力で幸せにする",
        "estado": "ativo",
        "genero": "Comédia, Escolar, Ficção Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/L/Love%20Comedy%20Manga%20ni%20Haitteshimatta%20node%2C%20Oshi%20no%20Make%20Heroine%20wo%20Zenryoku%20de%20Shiawase%20ni%20Suru/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Love Comedy Manga ni Haitteshimatta node, Oshi no Make Heroine wo Zenryoku de Shiawase ni Suru.jpg",
        "novo_capitulo": "",
        "historia": "No mundo de um mangá romance, popular, minha única missão como amigo do MC é fazer a heroína perdedora, Sei-chan, feliz! “Eu definitivamente vou fazer você feliz. Por favor, saia comigo.” “E-Espere, o que!? V-Você está falando sério…!?” A adaptação, em mangá do doce romance, da Kakuyomu começa agora!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "I",
        "nome": "Isekai De Tochi O Katte Noujou O Tsukurou",
        "tipo": "manga",
        "num_capitulos": 31,
        "lancamento": "2019",
        "Postado": "2023-04-26",
        "autor": "OKAZAWA Rokujuuyon",
        "artista": "SASAMEYUKI Jun",
        "nomes_alternativos": "Isekai de Tochi o Katte Noujou o Tsukurou, Let's Buy the Land and Cultivate in Different World, 在异世界购买土地建造农场, 異世界で土地を買って農場を作ろう",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comedia, Ecchi, Fantasia, Harem, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I/Isekai%20De%20Tochi%20O%20Katte%20Noujou%20O%20Tsukurou/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Isekai%20De%20Tochi%20O%20Katte%20Noujou%20O%20Tsukurou.jpg",
        "novo_capitulo": "",
        "historia": "Como nosso humilde corporativista Itonami Norio é repentinamente convocado para outro mundo, pareceria que ele seria enviado para um campo de batalha – ele, entretanto, não possui nenhuma habilidade para falar, e como ele é considerado inútil. Ele negocia com o rei e recebe um terreno – um terreno vazio e deserto, sem nenhum habitante à vista. Norio segura algo que ele não poderia contar a ninguém: O Mestre da Supremacia, um presente que lhe dará a mais confortável das vidas neste mundo. Aqui começa a colorida história de Norio – tendo uma sereia que ele pesca se declara sua esposa, tornando-se vizinha do Rei Morto-vivo, esta é sua vida ocupada, mas divertida – e agora um dragão aparece?!",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?",
        "tipo": "manga",
        "pasta": "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "I",
        "nome": "Isekai Kenkokuki",
        "tipo": "manga",
        "num_capitulos": 61,
        "lancamento": "2017",
        "Postado": "2022-05-01",
        "autor": "Sakuragi, Sakura",
        "artista": "KOIZUMI",
        "nomes_alternativos": "Different World Foundation, Otherworld Nation Founding Chronicles, Isekai Kenkoku-ki",
        "estado": "ativo",
        "genero": "Ação, Drama, Aventura, Fantasia, Harem, Isekai Romance, slice of life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I/Isekai%20Kenkokuki/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Isekai%20Kenkokuki.jpg",
        "novo_capitulo": "",
        "historia": "Um protagonista renascido em outro mundo. Aparentemente ele havia reencarnado como um filho abandonado, junto a outros órfãos. Para sobreviver, ele os conduziu à agricultura. Pouco a pouco, os órfãos se reuniram, e ao ouvir rumores de uma aldeia, outros começaram a migrar. O grupo que tinha sido nada além de crianças tornou-se uma aldeia antes que alguém percebesse. E então, vários países nos arredores começaram a observá-lo... Este é o conto épico do homem que mais tarde seria conhecido como o Imperador Divino.",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "R",
        "nome": "Release That Witch",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Release That Witch.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Survive On A Deserted Island With Beautiful Girls",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Survive On A Deserted Island With Beautiful Girls",
        "caminho-img": "./imgs/Survive On A Deserted Island With Beautiful Girls.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Fate/stay night",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Fate stay night",
        "caminho-img": "./imgs/Fate stay night-14.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "Isekai Yurutto Survival Seikatsu: Gakkou no Minna to Isekai no Mujintou ni Tenishitakedo Ore Dake Rakushou desu",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Isekai Yurutto Survival Seikatsu Gakkou no Minna to Isekai no Mujintou ni Tenishitakedo Ore Dake Rakushou desu",
        "caminho-img": "./imgs/Isekai Yurutto Survival Seikatsu Gakkou no Minna to Isekai no Mujintou ni Tenishitakedo Ore Dake Rakushou desu.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Martial God Asura",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Artes Marciais Aventura, Ação, Harem, Romance, Seinen, Sobrenatural",
        "pasta": "Martial God Asura",
        "caminho-img": "./imgs/Martial God Asura.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "M",
        "nome": "My Amazing Wechat",
        "tipo": "manhua",
        "num_capitulos": 162,
        "lancamento": 2023,
        "Postado": "2023-02-22",
        "autor": "iCiyuan",
        "artista": "iCiyuan",
        "nomes_alternativos": "Wo De Wei Xin Hen Niubi, 我的微信很牛逼, Meu WeChat é Incrível",
        "estado": "ativo",
        "genero": "Aventura, Ação, Ecchi, Escolar, Fantasia, Shounen, Romance, slice of life",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/M/My%20Amazing%20Wechat/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/imgs/My%20Amazing%20Wechat.jpg",
        "novo_capitulo": "",
        "historia": "Leo, um estudante universitário comum, é acidentalmente adicionado a um grupo de WeChat composto por figuras lendárias e poderosas, como o Rei dos Céus, a Mãe do Trovão e o Deus dos Milagres. Através desse grupo, Leo obtém acesso a itens mágicos e habilidades extraordinárias, transformando sua vida mundana em uma aventura, emocionante.",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Villainous Master Brings Along the Peerless Apprentices",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Ação, Artes Marciais Drama, Fantasia, Shounen",
        "pasta": "My Villainous Master Brings Along the Peerless Apprentices",
        "caminho-img": "./imgs/My Villainous Master Brings Along the Peerless Apprentices.webp",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 5.2,
        "id": "E",
        "nome": "Eu tive um filho do tirano",
        "tipo": "manhwa",
        "num_capitulos": 105,
        "lancamento": "2023",
        "Postado": "2022-02-26",
        "autor": "Ryuran,SF_JD",
        "artista": "SF_JD",
        "nomes_alternativos": "폭군의 아이를 가졌습니다, I Got Pregnant to the Tyrant’s Child",
        "estado": "completo",
        "genero": "Drama, fantasia, Historico Josei Romance",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/E/Eu%20tive%20um%20filho%20do%20tirano/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Eu%20tive%20um%20filho%20do%20tirano.jpg",
        "novo_capitulo": "",
        "historia": "Para Elan, o cavaleiro real, o festival de máscaras é uma rara chance de se soltar e relaxar. Mas sua noite de diversão rapidamente se transforma em uma manhã de horror quando ela acorda ao lado do implacável imperador Kylart. Sabendo o quão cruel ele pode ser com mulheres pegajosas, Elan foge, esperando que ele não tenha visto além de seu disfarce. Mas enquanto ela continua seus deveres estressantes de guardar o imperador, ela começa a sentir sintomas preocupantes de saúde. Uma ida ao médico revela que ela está grávida! Para piorar as coisas, há rumores de que Kylart está procurando a misteriosa mulher que conheceu na noite do festival. Elan pode manter seu segredo a salvo de todo o palácio, quando ela nem consegue controlar seus desejos constantes e enjôos matinais?</span>",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bloody Kiss (Yagami Rina)",
        "tipo": "manga",
        "status": "completo",
        "num_capitulos": "",
        "estado": "finalizado",
        "genero": "Romance, Shoujo, Sobrenatural",
        "pasta": "Bloody Kiss (Yagami Rina)",
        "caminho-img": "./imgs/Bloody Kiss (Yagami Rina).jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bloody Kiss",
        "tipo": "manga",
        "status": "completo",
        "num_capitulos": "",
        "estado": "finalizado",
        "genero": "Romance, Shoujo, Sobrenatural",
        "pasta": "Bloody Kiss",
        "caminho-img": "./imgs/Bloody Kiss.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bara to Juudan",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "completo",
        "genero": "Fantasia, Romance, Shoujo, Sobrenatural Vida_Escolar",
        "pasta": "Bara to Juudan",
        "caminho-img": "./imgs/Bara to Juudan.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Ai Hime ~ Ai to Himegoto",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "completo completo2",
        "genero": "Drama, Romance, Shoujo",
        "pasta": "Ai Hime ~ Ai to Himegoto",
        "caminho-img": "./imgs/Ai Hime ~ Ai to Himegoto.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bishounen, No Oheya",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "completo",
        "genero": "Comédia, Harem, Romance, Shoujo, Vida_Escolar",
        "pasta": "Bishounen, No Oheya",
        "caminho-img": "./imgs/Bishounen, No Oheya.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "Z",
        "nome": "Zatsuyou Fuyo Jutsushi ga Jibun no Saikyou ni Kizuku made",
        "tipo": "manga",
        "num_capitulos": 17,
        "estado": "ativo",
        "genero": "Ação, Fantasia, Shounen",
        "pasta": "Zatsuyou Fuyo Jutsushi ga Jibun no Saikyou ni Kizuku made",
        "caminho-img": "./imgs/Zatsuyou Fuyo Jutsushi ga Jibun no Saikyou ni Kizuku made.jpg",
        "novo_capitulo": "novo",
    },
    {
        "key": "of",
        "id": "O",
        "nome": "Otherworldly Magical Daoist Priest",
        "tipo": "manhwa",
        "num_capitulos": 40,
        "estado": "ativo",
        "genero": "Ação,, Artes Marciais, Comédia, Drama, Fantasia, Isekai, Magia, Shounen",
        "pasta": "Otherworldly Magical Daoist Priest",
        "caminho-img": "./imgs/Otherworldly Magical Daoist Priest.jpg",
        "novo_capitulo": "novo",
    },
    {
        "key": "of",
        "id": "O",
        "nome": "I’m in Trouble Because My Husband Is So Cute",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Ação,, Aventura,, Drama, Fantasia, Histórico, Josei, Romance, Seinen",
        "pasta": "I’m in Trouble Because My Husband Is So Cute",
        "caminho-img": "./imgs/I’m in Trouble Because My Husband Is So Cute.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "S",
        "nome": "Saenai Riman to Yankee Joshi Kousei",
        "tipo": "manga",
        "num_capitulos": 28,
        "lancamento": "2021",
        "Postado": "2023-02-22",
        "autor": "Tamaki Nao",
        "artista": "Tamaki Nao",
        "nomes_alternativos": "Business-Geek e Highschool-Punk, 冴えないリーマンとヤンキー女子高生",
        "estado": "ativo",
        "genero": "Comedia, Romance, slice of life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/S/Saenai%20Riman%20to%20Yankee%20Joshi%20Kousei/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Saenai%20Riman%20to%20Yankee%20Joshi%20Kousei.jpg",
        "novo_capitulo": "",
        "historia": "Yamada Hiroyuki tem 26 anos, tem um emprego estável, é um otaku, oprimido pelas ideias e pensamentos de sua família (quando você se casa? Você ainda assiste animes na sua idade?) Ele decide sair de casa e ir morar em um apartamento, sozinho e feliz, mas a imagem perfeita que ele tinha em mente quando se mudou, foi destruída quando soube que sua vizinha é uma yankee (delinquente) e ao mesmo tempo uma colegial, logo ele descobre que aquela garota rude e desbocada é alguém desajeitada, muito terna e muito fofa. A história desses dois jovens avançará para melhor?",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "W",
        "nome": "Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago",
        "tipo": "manhwa",
        "num_capitulos": 23,
        "estado": "ativo",
        "lancamento": "2022",
        "genero": "Drama, Fantasia, Romance, Shounen, Sobrenatural",
        "pasta": "Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago",
        "caminho-img": "./imgs/Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "E",
        "nome": "Estou Tentando Me Divorciar do Meu Esposo Vilão, Mas Teremos Um Filho",
        "tipo": "manhwa",
        "num_capitulos": 85,
        "lancamento": "2022",
        "Postado": "2022-02-22",
        "autor": "Tamaki Nao",
        "artista": "Tamaki Nao",
        "nomes_alternativos": "I Am Trying To Divorce My Villain Husband, But We Have A Child - I Plan to Divorce My Villain Husband, But We Have A Child - I Plan to Divorce My Villain Husband, Pero Tenemos un Hijo,- 악당 남편과 이혼하려는데,아이가 생겼다",
        "estado": "ativo",
        "genero": "Drama, Fantasia, Josei Romance",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhwas/E/Estou%20Tentando%20Me%20Divorciar%20do%20Meu%20Esposo%20Vil%C3%A3o%2C%20Mas%20Teremos%20Um%20Filho/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Estou%20Tentando%20Me%20Divorciar%20do%20Meu%20Esposo%20Vil%C3%A3o%2C%20Mas%20Teremos%20Um%20Filho.jpg",
        "novo_capitulo": "",
        "historia": "Ela possuiu a mulher que era casada com o diabo. Você desempenha o papel de alguém obcecada por um marido vilão. “Eu estarei ao seu lado!” Ela decidiu ser gentil com o marido, que mora na mesma casa que ela há muito tempo. Mas um dia, quando me tornei adulta e estava prestes a me divorciar… Uma má noite me deixou com uma criança inesperada. Então eu tentei sair antes que eles me pegassem. “Aquele Richard? Algo está errado com-” “Eu não quero deixar você ir, então morra em meus braços, Elisha.” Ela não conseguia se livrar disso enquanto tentava chorar e implorar com seu lindo rosto. “Para onde você vai fugir com meu filho?” Você me perseguiu com olhos tão frios? Acho que não posso escapar. O que eu faço agora?",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Childhood Friend Became an Obsessive Male Lead",
        "tipo": "manhwa",
        "num_capitulos": 46,
        "text_cap": "Capitulos: ",
        "lancamento": "2022",
        "estado": "ativo",
        "genero": "Drama, Fantasia, Josei Romance",
        "pasta": "My Childhood Friend Became an Obsessive Male Lead",
        "caminho-img": "./imgs/My Childhood Friend Became an Obsessive Male Lead.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "A Proprietária Bebê Está se Aposentando",
        "num_capitulos": 120,
        "tipo": "manhwa",
        "text_cap": "Capitulos: ",
        "estado": "ativo",
        "lancamento": "2022",
        "genero": "Fantasia, Romance, Shoujo",
        "pasta": "A Proprietária Bebê Está se Aposentando",
        "caminho-img": "./imgs/A Proprietária Bebê Está se Aposentando.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Three Tyrant Brothers",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Drama, Histórico Magia, Romance, Shoujo, Sobrenatural",
        "pasta": "My Three Tyrant Brothers",
        "caminho-img": "./imgs/My Three Tyrant Brothers.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "K",
        "nome": "Knight of the Frozen Flower",
        "tipo": "manhwa",
        "num_capitulos": 60,
        "lancamento": 2022,
        "Postado": "2022-05-05",
        "autor": "Jin Juha Towawa",
        "artista": "Towawa",
        "nomes_alternativos": "Ice Blossom Knight, Ice Flower Knight, 얼음꽃 기사",
        "estado": "ativo",
        "genero": "Acao Aventura, Drama, Fantasia, Historico Psicologico Romance, Shoujo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Knight%20of%20the%20Frozen%20Flower/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Knight%20of%20the%20Frozen%20Flower.jpg",
        "novo_capitulo": "",
        "historia": "Julia, que possuía grande esgrima, foi morta depois de ser usada pelo homem que amava. Seu único crime foi ter vivido uma vida com cara feia por causa de uma maldição… Logo antes de sua morte, ela testemunhou sua maldição se dissipando antes de retornar ao passado. Agora, ela jurou viver sua vida por si mesma.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "D",
        "nome": "De Tantas Coisas, Me Tornei um Corvo",
        "tipo": "manhwa",
        "num_capitulos": 97,
        "lancamento": 2022,
        "Postado": "2023-01-05",
        "autor": "Sylvester",
        "artista": "Glee",
        "nomes_alternativos": "Off All Things’ I Became a Crow, 하필이면 까마귀가 되어버렸다",
        "estado": "ativo",
        "genero": "Fantasia, Romance, Shoujo, Sobrenatural",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/De%20Tantas%20Coisas%2C%20Me%20Tornei%20um%20Corvo/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/De%20Tantas%20Coisas%2C%20Me%20Tornei%20um%20Corvo%202.jpeg",
        "novo_capitulo": "",
        "historia": "Depois de morrer em um acidente, ela reencarnou em um jogo do gênero otome… Como um corvo! Não acredito que sou um corvo! Nem pra eu ser uma figurante! Quando eu estava observando a primeira pessoa que apareceu para mim… Era o príncipe herdeiro. “Como você pode ser tão amável, Reinelle?” Cawk, cawk caek (Me leve contigo e me crie!)” O príncipe herdeiro, Kameut, me deu um nome e me tratou com carinho. Eu sou um corvo, afinal. Não vai ter problema se eu tratá-lo com amor ou se meu coração, se revira por ele. Não tinha problema até… “Olá, Reinelle?” “O que aconteceu de repente comigo?” Depois de morrer em um acidente, ela reencarnou em um jogo do gênero otome… Como um corvo! Não acredito que sou um corvo! Nem pra eu ser uma figurante! Quando eu estava observando a primeira pessoa que apareceu para mim… Era o príncipe herdeiro. “Como você pode ser tão amável, Reinelle?” Cawk, cawk caek (Me leve contigo e me crie!)” O príncipe herdeiro, Kameut, me deu um nome e me tratou com carinho. Eu sou um corvo, afinal. Não vai ter problema se eu tratá-lo com amor ou se meu coração, se revira por ele. Não tinha problema até… “Olá, Reinelle?” “O que aconteceu de repente comigo?”",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "N",
        "nome": "Nihon e Youkoso Elf-san",
        "tipo": "manga",
        "num_capitulos": 40,
        "lancamento": "2018",
        "Postado": "2022-02-22",
        "autor": "Makishima Suzuki",
        "artista": "Shimo Aono",
        "nomes_alternativos": "Welcome to Japan, Elf-san",
        "estado": "ativo",
        "genero": "Aventura, Comédia, Ecchi, Fantasia, Romance, Shounen, slice of life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/N/Nihon%20e%20Youkoso%20elf-san/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Nihon%20e%20Youkoso%20elf-san.jpg",
        "novo_capitulo": "",
        "historia": "Kitase Kazuhiro é um assalariado comum que sempre deixa o escritório na hora certa. Embora este seja o Japão, talvez ele não seja realmente comum, afinal. O que é verdadeiramente estranho vem depois disso; Toda noite, ele toma banho, troca seu pijama e tem uma boa noite de sono, em seguida, ele sonha com um mundo de fantasia, e só acorda quando ele morre ou dorme nesse mundo. Um dia, ele morreu depois de tropeçar no covil de um dragão. Nisso ele tem “Um pesadelo”, ele fica amuado, até que ele encontra sua amiga elfo em sua cama. Curioso para ver um elfo waifu experimentar a vida cotidiana no Japão? Como é andar com a fantasia, de todo homem nas ruas de Tóquio? Este mangá é para todos vocês amantes de elfos por aí!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "A",
        "nome": "A 99° Noiva do Duque",
        "tipo": "manhwa",
        "num_capitulos": 53,
        "lancamento": 2022,
        "Postado": "2023-02-22",
        "autor": "Lisabel",
        "artista": "ALLYN",
        "nomes_alternativos": "The Duke’s 99th Bride, The 99th Bride of the Duke, 공작가의 99번째 신부",
        "estado": "ativo",
        "genero": "Drama, Fantasia, Romance, Shoujo",

        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/A/A%2099%20Noiva%20do%20Duque/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/A 99° Noiva do Duque.jpg",
        "novo_capitulo": "",
        "historia": "Grace, que perdeu a mãe e ficou órfã, vivia na rua esperando sua morte, foi salva por Penelope Erdona e se tornou Grace Erdona. Um dia, enquanto ela e Penelope estavam juntas, Penelope falou sobre se casar. A pessoa com quem ela deve se casar não é outro senão o duque de Felton, a família mais poderosa do mundo. Corria o boato de que todas as mulheres que ali se casavam haviam desaparecido ou voltado com um estado mental muito estranho. Para proteger Penelope, Grace pretende se casar com o duque em seu lugar. ‘Ouvi dizer que esta não é a primeira vez que você se casa, posso saber quantas vezes é?’ – Deixe-me ver … você é a 99º. Grace Erdona, acorde!",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "I",
        "nome": "Fairy, Wait a Moment! Please Listen to My Argument",
        "tipo": "manhua",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Acao Aventura, Drama, Fantasia, Shounen",
        "pasta": "Fairy, Wait a Moment! Please Listen to My Argument",
        "caminho-img": "./imgs/Fairy, Wait a Moment! Please Listen to My Argument.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "B",
        "nome": "Bon Appétit!",
        "tipo": "manhwa",
        "num_capitulos": 162,
        "lancamento": 2022,
        "Postado": "2023-02-22",
        "autor": "Miso",
        "artista": "Kyun",
        "nomes_alternativos": "맛본김에, Depois de Provar",
        "estado": "ativo",
        "genero": "Drama, Romance, Shoujo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Bon%20App%C3%A9tit!/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Bon Appétit!.jpg",
        "novo_capitulo": "",
        "historia": "“Você está comendo numa situação, dessas?” “É claro! Eu tenho que saborear até morrer. Você quer um?” Ela foi reincarnada em uma novel como Ruana, a princesa abandonada. E sua morte já estava decidida. Ela só queria deixar as pessoas saberem de seus dons culinários, mas ela foi confundida com uma bruxa por causa do seu bife jerky com queijo! O general do exército conquistador, Duque Legion, que perdeu seu paladar, a levou para o império por conta dos seus bife jerkies deliciosos e para quebrar a maldição que era passada de geração, em geração,.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "A",
        "nome": "Ano Oni Kyoushi ga Boku no Ane ni Narundesuka",
        "tipo": "manga",
        "num_capitulos": 22,
        "lancamento": "2020",
        "Postado": "2022-02-26",
        "autor": "Nekomata Nuko",
        "artista": "Seiji Matsuyama",
        "nomes_alternativos": "Is that demon teacher my sister?, That Demonic Teacher Will Be My Sister?",
        "estado": "ativo",
        "genero": "Comedia, Ecchi, Escolar, Romance, Shounen, slice of life",
        "pasta": "https://oclubedosdez.github.io/Imagens/mangas/Ano%20Oni%20Kyoshi%20ga%20Boku%20no%20Ane%20ni%20Narundesuka/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Ano%20Oni%20Kyoshi%20ga%20Boku%20no%20Ane%20ni%20Narundesuka.jpg",
        "novo_capitulo": "",
        "historia": "A história acompanha um rapaz que inicialmente fica muito feliz com a notícia de ter uma irmã mais velha devido ao seu pai se casar novamente com uma mulher que já tem uma filha, até que ele descobre que a sua nova irmã é na realidade a sua estrita professora de educação, física da sua escola, Shina. Com o pai saindo de casa para morar com a sua nova esposa, o rapaz vai morar sozinho com a sua nova irmã. Na sua nova vida juntos, o rapaz descobre que Shina no trabalho é completamente diferente da Shina em casa: desajeitada, com medo de insetos e gentil.",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "I",
        "nome": "I’m Not a Demon",
        "tipo": "manhua",
        "num_capitulos": 19,
        "lancamento": "2023",
        "estado": "ativo",
        "genero": "Acao Aventura, Drama, Fantasia, Shounen",
        "pasta": "I’m Not a Demon",
        "caminho-img": "./imgs/I’m Not a Demon.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "K",
        "nome": "Kekkon Yubiwa Monogatari",
        "tipo": "manga",
        "num_capitulos": 62,
        "lancamento": 2016,
        "Postado": "2020-03-22",
        "autor": "Maybe",
        "artista": "Maybe",
        "nomes_alternativos": "Tales of Wedding Rings",
        "estado": "ativo",
        "genero": "Ação, Ecchi, Fantasia, Harem, Magia, Romance, Seinen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Kekkon%20Yubiwa%20Monogatari/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Kekkon%20Yubiwa%20Monogatari.jpg",
        "novo_capitulo": "",
        "historia": "Satou é apaixonado por sua amiga de infância e vizinha, Hime, desde que ela e o avô apareceram do nada há 10 anos. Agora uma deslumbrante, mas ainda misteriosa estudante, ela torna mais difícil para Satou confessar seus sentimentos. Com o convite de Hime para ir ao festival de verão, ele vai conseguir reunir coragem para transformar sua amizade em algo mais? Ou aguardará este casal um destino totalmente diferente?",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "B",
        "nome": "Beware of the Brothers!",
        "tipo": "manhwa",
        "num_capitulos": 90,
        "lancamento": 2020,
        "Postado": "2022-02-22",
        "autor": "Plutus",
        "artista": "Shimo Aono",
        "nomes_alternativos": "Cuidado com os irmãos!, 그 오빠들을 조심해!",
        "estado": "ativo",
        "genero": "Drama, Fantasia, Historico Romance, Shoujo",

        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Beware%20of%20the%20Brothers/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Beware%20of%20the%20Brothers!.jpg",
        "novo_capitulo": "",
        "historia": "Hari foi adotada pelo duque Ernst aos 7 anos, quando perdeu sua mãe. Embora ela tenha recebido todo tipo de perseguição dos três filhos de Ernst, ela finalmente conseguiu escapar daquela vida que causou sangue e lágrimas quando ela estava prestes a se casar. “Mas o que é isso? Quando acordei do meu sonho, voltei àquela infância infernal! Isso é um sonho ?!” “Hmph. Se eu não consigo acordar desse sonho, pelo menos vou viver sem muita consideração, pelos outros agora!” É assim que a história de Hari começa!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "A",
        "nome": "Atenciosamente: Me Tornei a Empregada do Duque",
        "tipo": "manhwa",
        "num_capitulos": 111,
        "lancamento": 2020,
        "Postado": "2021-02-26",
        "autor": "Jooahri",
        "artista": "Aloha",
        "nomes_alternativos": "Sincerely: I Became a Duke's Maid, A Tender Heart: The Story of How I Became a Duke's Maid, 날것: 공작가의 하녀로 빙의했습니다",
        "estado": "completo",
        "genero": "Fantasia, Isekai Romance, Shoujo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Sincerely%20I%20Became%20a%20Duke's%20Maid/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Atenciosamente%20Me%20Tornei%20a%20Empregada%20do%20Duque.jpg",
        "novo_capitulo": "",
        "historia": "Alejandro foi atingido por uma terrível maldição ainda jovem, evitado por sua família e rejeitado por todos. Como personagem coadjuvante de um romance, ele está condenado a um papel de miséria e solidão. Isto é, até que um leitor simpático é repentinamente transportado para este mundo fictício como sua humilde empregada, determinado a mudar seu destino! Evelina pode libertar Alejandro de seu destino miserável e ajudá-lo a encontrar o amor verdadeiro?",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "C",
        "nome": "Circunstâncias da Irene",
        "tipo": "manhwa",
        "num_capitulos": 58,
        "lancamento": 2022,
        "Postado": "2023-01-01",
        "autor": "Bok Sung Ah, Mongsu",
        "artista": "MStoryHub",
        "nomes_alternativos": "iraine’s circumstances, 아이린의 상황",
        "estado": "completo",
        "genero": "Drama, Fantasia, Josei Romance",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Circunstancias%20da%20Irene/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Circunst%C3%A2ncias%20da%20Irene.jpg",
        "novo_capitulo": "",
        "historia": "Irene, que passou sua vida de forma humilde, pensou que sua vida estava mudando depois da princesa reconhecer suas habilidades. No entanto, ela se apaixonou por alguém que não deveria. Até tentou fechar os seus olhos de forma silenciosa, mas… “Não tire os olhos de mim.” “Por que está interessado em mim?” Diferente das duras palavras, preciso suportar a vida de uma empregada no palácio imperial e também a tentação, de um lindo homem que emana um doce e nobre odor que não consigo me esquecer. “Irei ficar bem?”",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "F",
        "nome": "Fuufu Ijou, Koibito Miman",
        "tipo": "manga",
        "num_capitulos": 68,
        "lancamento": 2020,
        "Postado": "2021-01-10",
        "autor": "Yuuki Kanamaru",
        "artista": "Yuuki Kanamaru",
        "nomes_alternativos": "夫婦以上、恋人未満",
        "estado": "ativo",
        "genero": "Comedia, Drama, Escolar, Romance, slice of life",

        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Fuufu%20Ijou%2C%20Koibito%20Miman/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Fuufu%20Ijou%2C%20Koibito%20Miman.jpg",
        "novo_capitulo": "",
        "historia": "Jirou, um terceiro ano do ensino médio, é forçado a viver com um gyaru chamado Akari em um curso chamado “Prático de Casal”. A fim de serem emparelhados com seus próprios interesses românticos, eles vão agir como um casal…!?",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "K",
        "nome": "kikan shita yuusha no gojitsudan",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Comédia, Ecchi, Fantasia, Harem, Romance, Magia, Shounen, Isekai",
        "pasta": "kikan shita yuusha no gojitsudan",
        "caminho-img": "./imgs/kikan shita yuusha no gojitsudan.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "I Confessed to the Boss",
        "tipo": "manhwa",
        "num_capitulos": 59,
        "lancamento": "2021",
        "estado": "ativo",
        "genero": "Comedia, Drama, Josei Romance, Shoujo",
        "pasta": "I Confessed to the Boss",
        "caminho-img": "./imgs/I Confessed to the Boss.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "P",
        "nome": "Pretendente Surpresa",
        "tipo": "manhwa",
        "status": "completo",
        "num_capitulos": 124,
        "lancamento": "2020",
        "estado": "completo",
        "genero": "Comedia, Drama, Josei Romance, slice of life",
        "pasta": "Pretendente Surpresa",
        "caminho-img": "./imgs/Pretendente Surpresa.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "Q",
        "nome": "Quando a Filha Ilegítima do Conde se Casa",
        "tipo": "manhwa",
        "num_capitulos": 79,
        "lancamento": "2022",
        "estado": "ativo",
        "genero": "Comédia, Drama, Josei Romance, slice of life",
        "pasta": "Quando a Filha Ilegítima do Conde se Casa",
        "caminho-img": "./imgs/Quando a Filha Ilegítima do Conde se Casa.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Adelaide",
        "tipo": "manhwa",
        "status": "completo",
        "num_capitulos": 85,
        "lancamento": "2017",
        "estado": "completo",
        "genero": "Fantasia, Histórico Isekai Romance",
        "pasta": "Adelaide",
        "caminho-img": "./imgs/Adelaide.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "A",
        "nome": "A protagonista feminina está tentando me tornar sua madrasta",
        "tipo": "manhwa",
        "num_capitulos": 72,
        "lancamento": 2021,
        "Postado": "2022-01-22",
        "autor": "moggamgi",
        "artista": "halihin",
        "nomes_alternativos": "Tricked Into Becoming the heroine's Stepmother, Heugmag Yeojuga Nal Saeeommalo Mandeullyeogo Hae, Éminence Grise Female Lead Is Trying to Make Me Her Stepmom",
        "estado": "ativo",
        "genero": "Fantasia, Historico Josei Romance, Shoujo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/A%20protagonista%20feminina%20est%C3%A1%20tentando%20me%20tornar%20sua%20madrasta/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/A%20protagonista%20feminina%20est%C3%A1%20tentando%20me%20tornar%20sua%20madrasta.jpg",
        "novo_capitulo": "",
        "historia": 'Acordei no corpo do personagem da máfia Civil 1 no "romance, trágico" que escrevi com meus amigos para me divertir. E desde que o duque Henstone, o pai da protagonista feminina, inicia uma revolução para mudar o futuro infeliz de sua filha, muitas vidas estarão em perigo se eu deixar assim. "Eu protegerei a protagonista feminina!" E foi assim que comecei a viver com a filha do duque idiota. Mas por alguma razão, a pequena liderança feminina é um pouco estranha. "Por que você continua tentando me conectar com seu pai?"',
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "A",
        "nome": "A Relação, Simbiótica Entre uma Coelha e Uma Pantera Negra",
        "tipo": "manhwa",
        "num_capitulos": 125,
        "lancamento": 2021,
        "Postado": "2022-02-22",
        "autor": "Yasik, Mogin",
        "artista": "Sadam",
        "nomes_alternativos": "The Symbiotic Relationship Between a Panther and a Rabbit, TOKKIWA HEUGPYOBEOM UI GONGSAENG GWANGYE, THE MUTUAL RELATIONSHIP BETWEEN THE RABBIT AND THE BLACK PANTHER",
        "estado": "ativo",
        "genero": "Aventura, Comedia, Drama, Fantasia, Romance, Shoujo, Sobrenatural",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/A%20Rela%C3%A7%C3%A3o%20Simbi%C3%B3tica%20Entre%20uma%20Coelha%20e%20Uma%20Pantera%20Negra/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/A%20Rela%C3%A7%C3%A3o%20Simbi%C3%B3tica%20Entre%20uma%20Coelha%20e%20Uma%20Pantera%20Negra.jpg",
        "novo_capitulo": "",
        "historia": "Vivi é uma… meia-coelha?! Como uma criatura que deveria ter a capacidade de se transformar em humana, Vivi é um fracasso, tida como amaldiçoada e enviada à sua morte. Felizmente, o seu tormento é interrompido quando Ahin do clã da Pantera Negra a salva. Mas com cada ameaça e comando que esse herdeiro temperamental faz para Vivi, ela questiona a sua segurança (e a sua sanidade). Cercada por carnívoros e seus feromônios poderosos, ela vai tentar sobreviver o caos enquanto presa na sua forma de coelho. Ela vai conseguir descobrir como se transformar e utilizar o poder dentro do seu adorável e felpudo ser?",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "I",
        "nome": "I Time-Traveled and Confessed to My Teacher Crush",
        "tipo": "manga",
        "num_capitulos": 55,
        "lancamento": 2019,
        "Postado": "2022-01-05",
        "autor": "Kennoji & Matsumoto",
        "artista": "Komikan",
        "nomes_alternativos": "KOU 2 NI TIME LEAPED SHITA ORE GA, TOUJI SUKI DATTA SENSEI NI KOKUTTA KEKKA,",
        "estado": "completo",
        "genero": "slice of life Romance, Comedia, Escolar, Viagem-no-tempo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I%20Time-Traveled%20and%20Confessed%20to%20My%20Teacher%20Crush/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/I%20Time-Traveled%20and%20Confessed%20to%20My%20Teacher%20Crush.jpg",
        "novo_capitulo": "",
        "historia": "Eu era um trabalhador corporativo nos meus 30 anos, quando acordei e descobri que tinha voltado no tempo para a primavera do segundo ano do ensino médio. Naquela época, havia uma professora que eu me arrependi por não ter me confessado, então no calor do momento eu me confessei a ela, e agora estamos namorando! No entanto, a professora é pessoa que faria qualquer pessoa um homem bom para nada, então acabei sendo muito mimado por ela. Enquanto secretamente saio com a minha professora (namorada), uma doce vida escolar, cheia de paquera me aguarda. Um segundo ano do ensino médio com meus 30 anos no interior e a professora (namorada) que eu quero mimar, nossa comédia, romântica cotidiana começa.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "E",
        "nome": "Eu Domei o Protagonista Masculino Que Tentou me Matar",
        "tipo": "manhwa",
        "num_capitulos": 25,
        "lancamento": 2023,
        "Postado": "2023-02-22",
        "autor": "sugarjamong",
        "artista": "STUDIO M",
        "nomes_alternativos": "I Tamed the Male Lead Who Tried to Kill Me, 나를 죽일 남주를 길들여버렸다",
        "estado": "ativo",
        "genero": "Drama, Fantasia, Romance, Shoujo",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/Eu%20Domei%20o%20Protagonista%20Masculino%20Que%20Tentou%20me%20Matar/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Eu%20Domei%20o%20Protagonista%20Masculino%20Que%20Tentou%20me%20Matar.jpg",
        "novo_capitulo": "",
        "historia": "A família de Latia acolheu Karshian quando seu pai foi em uma expedição marítima, mas depois de rumores de sua morte, eles passam a tratar Karshian como um parasita. Instigada por seus pais sádicos e desesperada por sua aprovação,, Latia intimida Karshian implacavelmente. No entanto, quando o pai de Karshian retorna como um herói nacional e poderoso duque, Karshian se vinga executando toda a família de Latia! E, em seu último suspiro, ela percebe que sua família esteve mentindo o tempo todo. Então, ao reencarnar, ela está determinada a evitar sua morte e tratar Karshian decentemente. Porém, isso não será fácil, já que Karshian desconfia de cada movimento de Latia. Latia será capaz de conquistar Karshian e virar o jogo contra sua família desta vez, ou ela está fadada a morrer pelas mãos de Karshian mais uma vez?",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "S",
        "nome": "Salvos A Monster Evolution LitRPG",
        "tipo": "manhwa",
        "num_capitulos": 35,
        "lancamento": 2023,
        "Postado": "2023-05-01",
        "autor": "MelasDelta",
        "artista": "KP Comics Studios",
        "nomes_alternativos": "Salvos (A Monster Evolution LitRPG)",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comedia, Drama, Fantasia, Jogo Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/Salvos%20A%20Monster%20Evolution%20LitRPG/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/pages/manhwas/imgs/Salvos A Monster Evolution LitRPG.jpg",
        "novo_capitulo": "",
        "historia": "Siga Salvos, uma garota demoníaca com uma tendência a fazer amigos e socar idiotas em suas regiões inferiores. É uma história sobre ação,, aventura, e evolução. Segue a jornada desde seu nascimento e à medida que ela cresce e ganha experiência ao encontrar coisas novas através das várias lentes de sua vida.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "M",
        "nome": "Musume ja Nakute Mama ga Suki nano",
        "tipo": "manga",
        "num_capitulos": 30,
        "lancamento": 2020,
        "Postado": "2022-03-22",
        "autor": "NOZOMI Kouta",
        "artista": "AZUMA Tesshin",
        "nomes_alternativos": "Musume Janakute, Watashi (Mama) ga Suki Nano!?, You Like Me (Mama), Not My Daughter!?, 娘じゃなくて私が好きなの？！",
        "estado": "ativo",
        "genero": "Comedia, Romance, slice of life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Musume%20ja%20Nakute%20Mama%20ga%20Suki%20nano/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Musume%20ja%20Nakute%20Mama%20ga%20Suki%20nano.jpg",
        "novo_capitulo": "",
        "historia": "Esta é uma comédia, romântica estrelada por uma mulher adulta de 34 anos chamada Ayako, ela recebe uma confissão de um homem 14 anos mais novo que ela, o estudante universitário de 20 anos, Takumi… Um homem que ela conhecia como o inocente “Takkun” que mora ao lado e que é tutor de sua filha adotiva desde os 10 anos. A revelação, a espanta, pois ela pensava que sua filha, Miu e ele eram um casal de namorados. PRESENCIE O MANGÁ MAIS ESPERADO EM 7 REINOS, DELICIE-SE COM AS MARAVILHOSAS AVENTURA,S DESSA MIILF SENSACIONAL!!!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "S",
        "nome": "Saint Seiya Meiou Iden Dark Wing",
        "tipo": "manga",
        "num_capitulos": 29,
        "lancamento": "2020",
        "Postado": "2023-03-22",
        "autor": "Masami Kurumada . Kenji Saito",
        "artista": "Nobufune Ueda",
        "nomes_alternativos": "聖闘士星矢 冥王異伝ダークウイング",
        "estado": "ativo",
        "genero": "Ação, Aventura, Fantasia, Shounen, Sobrenatural",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Saint%20Seiya%20Meiou%20Iden%20Dark%20Wing/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Saint Seiya Meiou Iden Dark Wing.jpg",
        "novo_capitulo": "",
        "historia": "Um estudante do ensino médio sofre um acidente e acorda no Elíseo do Mundo dos Mortos. Em busca de respostas, ele se encontra com Hades, o Deus do Submundo.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.1,
        "id": "C",
        "nome": "Congelamento Global",
        "tipo": "manhua",
        "num_capitulos": 7,
        "lancamento": 2023,
        "Postado": "2023-01-01",
        "autor": "记忆的海",
        "artista": "记忆的海",
        "nomes_alternativos": "Quan Qiu Bing Feng: Wo Dazaole Mori Anquan Wu, Global Freeze: I Created an Apocalypse Shelter, 全球冰封：我打造了末日安全屋",
        "estado": "ativo",
        "genero": "Ação, Aventura, Romance, Sobrevivência",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhuas/Congelamento%20Global/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhuas/img/Congelamento Global.jpg",
        "novo_capitulo": "",
        "historia": "O mundo entra em uma era gélida e 95% da humanidade foi exterminada! Durante a sua vida anterior, Zhang Yi foi tragicamente morto pelas pessoas que ajudou de bom grado, mas Zhang Yi recebeu uma segunda chance e agora tem a habilidade de manipulação, do espaço capaz de armazenar tudo o que desejar. Para se preparar, ele começou a estocar muita comida para viver em um mundo congelado e fazer aqueles que o mataram, sofrer muito!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.1,
        "id": "T",
        "nome": "Tanbo de Hirotta Onna Kishi, Inaka de Ore no Yome dato Omowareteiru",
        "tipo": "manga",
        "num_capitulos": 10,
        "lancamento": 2023,
        "Postado": "2023-01-01",
        "autor": "Renkinou",
        "artista": "Otoha Saori",
        "nomes_alternativos": "田んぼで拾った女騎士, 田舎で俺の嫁だと思われている",
        "estado": "ativo",
        "genero": "Fantasia, Romance, Shounen, slice of life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Tanbo%20de%20Hirotta%20Onna%20Kishi%2C%20Inaka%20de%20Ore%20no%20Yome%20dato%20Omowareteiru/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Tanbo de Hirotta Onna Kishi, Inaka de Ore no Yome dato Omowareteiru.jpg",
        "novo_capitulo": "",
        "historia": "Jin Mita, um fazendeiro que vive em uma pequena cidade do interior, descobre uma cavaleira inconsciente em seu campo de arroz uma manhã. Ela se chama Seraphim, e parece ter vindo de outro mundo. Ela não tem conhecimento deste mundo e não tem para onde ir. Incapaz de suportar vê-la assim, Jin se ofereceu para acolhê-la, mas aparentemente as pessoas ao seu redor pensam que Seraphim é sua esposa…!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "E",
        "nome": "Eternamente Level 1 Até A Morte",
        "tipo": "manga",
        "num_capitulos": 30,
        "lancamento": 2021,
        "Postado": "2021-05-01",
        "autor": "Miraijin A",
        "artista": "Uemukai, Dai",
        "nomes_alternativos": "Genkai Level 1 kara no Nariagari: Saijaku Level no Ore ga Isekai Saikyou ni Naru made, 限界レベル１からの成り上がり:～最弱レベルの俺が異世界最強になるまで～",
        "estado": "ativo",
        "genero": "Ação, Aventura, Fantasia, Harem, Romance, Isekai Magia",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Eternamente%20Level%201%20At%C3%A9%20A%20Morte/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Eternamente Level 1 Até A Morte.jpg",
        "novo_capitulo": "",
        "historia": "Tetsuya Takahashi foi subitamente convocado para outro mundo. No entanto, sua invocação, foi um erro e depois de participar da revisão de Level… ele tem o [Limite de Level] mais fraco o lvl.1, o rei vendo seu limite o chama de “defeituoso” e o condena à morte! Apesar de ter sido convocado contra sua vontade, Tetsuya é jogado no vale dos monstros. Lá ele foi atacado e levado à beira da morte e, quando usou sua habilidade única [Corpse Absortion] e ganha as habilidades que o cadáver possuía! Vamos lá! Sobreviva neste mundo, torne-se forte e vingue-se daqueles que o descartaram. O homem de lvl. 1 que foi chamado de defeituoso e fraco… agora começa a ascensão para ser o mais forte!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "M",
        "nome": "Mushoku no Eiyuu: Betsu ni Skill Nanka Iranakattan daga",
        "tipo": "manga",
        "num_capitulos": 19,
        "lancamento": 2018,
        "Postado": "2020-10-01",
        "autor": "KUZU Shichio",
        "artista": "NANAE Akio, UEDA Yumehito",
        "nomes_alternativos": "I did not need something like skills as an unemployed hero, The Classless Hero: I Didn't Need Skills Anyway, The hero who has no class. I don't need any skills, it's okay, 無職の英雄 別にスキルなんか要らなかったんだが",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comedia, Fantasia, Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Mushukou%20no%20Eiyuu%20Betsu%20Ni%20Skill%20Nanka%20Iranakattan%20Daga/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Mushoku no Eiyuu Betsu ni Skill Nanka Iranakattan daga.jpg",
        "novo_capitulo": "",
        "historia": "“Classes” são dadas aos 10 anos de idade, e a presença ou ausência de “habilidades” afeta a vida fortemente. Arel, o filho de Fara, a princesa da espada, e de Leon, o rei da magia, foi reconhecido como “Sem classe”… Perdendo então oportunidades de trabalho, Arel acredita que ele consegue perseverar por meio de esforço.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "S",
        "nome": "Shinigami ni Sodaterareta Shoujo, wa Shikkoku no Tsurugi wo Mune ni Idaku",
        "tipo": "manga",
        "num_capitulos": 17,
        "lancamento": 2019,
        "Postado": "2020-02-22",
        "autor": "Ayamine Maito",
        "artista": "Matsukaze Suiren",
        "nomes_alternativos": "Death Girl, Shinigami ni Sodaterareta Shoujo, wa Shikkoku no Ken wo Mune ni Idaku, The Girl Raised by the Death God Holds the Sword of Darkness in Her Arms, The Little Girl Raised by Death Holds the Sword of Death Tightly, 사신에게 길러진 소녀는 칠흑의 검을 가슴에 품는다",
        "estado": "ativo",
        "genero": "Ação, Aventura, Fantasia, Misterio, Romance, Seinen, Sobrenatural",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Shinigami%20ni%20Sodaterareta%20Shoujo%20wa%20Shikkoku%20no%20Tsurugi%20wo%20Mune%20ni%20Idaku/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Shinigami%20ni%20Sodaterareta%20Shoujo%20wa%20Shikkoku%20no%20Tsurugi%20wo%20Mune%20ni%20Idaku.jpg",
        "novo_capitulo": "",
        "historia": "No fundo de um santuário esquecido dentro da floresta, um bebê é encontrado por figuras sombrias, os Shinigamis. Um deles, Zett, a pegou para usá-la como “objeto de observação” contra o desejo de seus irmãos que queriam comer a sua alma. Zett lhe deu vários conhecimentos e a treinou para lutar. Até que um dia ele de repente desapareceu, deixando-lhe uma carta e uma espada negra. Então, tendo crescido, Olivia saiu em busca de Zett. Esta é a história de Olivia Valedstorm, a garota criada pela morte, enquanto muda o curso da guerra com seu temido título de Shinigami.",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "B",
        "nome": "Bannou “Murazukuri” Cheat de Otegaru Slow Life ~Mura desu ga Nani ka?~",
        "tipo": "manga",
        "num_capitulos": 5,
        "lancamento": 2023,
        "Postado": "2023-02-22",
        "autor": "Kuzu Shichio",
        "artista": "Kaidouj1",
        "nomes_alternativos": "The Amazing Village Creator: Slow Living with the Village Building Cheat Skill,Amazing Muradukuri",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comedia, Fantasia, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Bannou%20%E2%80%9CMurazukuri%E2%80%9D%20Cheat%20de%20Otegaru%20Slow%20Life%20%7EMura%20desu%20ga%20Nani%20ka%7E/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Bannou%20%E2%80%9CMurazukuri%E2%80%9D%20Cheat%20de%20Otegaru%20Slow%20Life%20%7EMura%20desu%20ga%20Nani%20ka%7E.jpg",
        "novo_capitulo": "",
        "historia": "Ao receber o estranho dom de construir vilas, Luke, filho de um lorde, é expulso de seu domínio por vergonha. Ele chega a uma terra árida com planos de desenvolvê-la da melhor forma possível e de viver uma vida simples e tranquila… quando, de repente, seu misterioso dom é ativado! Desfrute da vida incrível e tranquila de Luke e veja como sua aldeia cresce, seu dom aumenta de nível e suas capacidades de construção de aldeia se transformam nesta nova série cômica!",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.5,
        "id": "L",
        "nome": "Lilia’s Pregnancy Spells the World’s End",
        "tipo": "manga",
        "num_capitulos": 3,
        "lancamento": 2023,
        "Postado": "2024-02-25",
        "autor": "Sakayama Shinta",
        "artista": "Sakayama Shinta",
        "nomes_alternativos": "Lilia Pregant The Word End, リリア・プレグナント・ザ・ワールド・エンド",
        "estado": "ativo",
        "genero": "Comedia, Ecchi, Fantasia, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/L/Lilia's%20Pregnancy%20Spells%20the%20World's%20End/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Lilia%E2%80%99s%20Pregnancy%20Spells%20the%20World%E2%80%99s%20End.jpg",
        "novo_capitulo": "",
        "historia": "O mundo será destruído se você fizer sexo com a filha do Rei Demônio.” Depois de derrotar o Rei Demônio e salvar o outro mundo, o herói Takahiro retorna ao mundo real. Um dia, Lilia, filha do Rei Demônio, chega de repente na casa de Takahiro, onde ele leva uma vida tranquila. Takahiro se prepara para a vingança, mas o objetivo dela é gerar um filho do forte do Takahiro…!?",
        "CapituloInicia": 1,
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Atsumori-kun no Oyome-san",
        "tipo": "manga",
        "num_capitulos": 16,
        "lancamento": "2018",
        "estado": "ativo",
        "genero": "Comedia, Drama, Romance, Shoujo, slice of life",
        "pasta": "Atsumori-kun no Oyome-san",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Atsumori-kun%20no%20Oyome-san.jpg",
        "novo_capitulo": "",
    },
    {
        "key": "on",
        "nota": 5,
        "id": "M",
        "nome": "Maga da Culinária",
        "tipo": "manhwa",
        "num_capitulos": 38,
        "lancamento": 2022,
        "Postado": "2023-02-05",
        "autor": "Ppili Ppala",
        "artista": "Purple Lemon & Dahan",
        "nomes_alternativos": "Cooking Sorcerer, 요리하는 마법사",
        "estado": "ativo",
        "genero": "Comedia, Fantasia, Romance",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/M/Maga%20da%20Culin%C3%A1ria/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Maga%20da%20Culin%C3%A1ria2.jpg",
        "novo_capitulo": "",
        "historia": "Uma tatuadora e amante de comida, YooJung, perdeu a consciência devido a um acidente repentino e, quando abre seus olhos, se vê no corpo de “Sylvia”, uma personagem de um romance, que tinha lido recentemente. Além disso, ela passa a conhecer Felix, o herói da novel que, devido aos abusos de sua madrasta, está sofrendo de anorexia e em breve transformará o continente em um mar de sangue. Para que consiga comer mais comidas deliciosas e cozinhar com maior facilidade, Sylvia passa a treinar a criação, de círculos mágicos em seu corpo. Seus novos círculos mágicos, criados com suas próprias mãos, serão capazes de trazer uma nova esperança ao continente?",
        "CapituloInicia": 1,
    },
    {
        "key": "on",
        "nota": 4.9,
        "id": "U",
        "nome": "um garoto na escola feminina",
        "tipo": "manhua",
        "num_capitulos": 356,
        "lancamento": 2018,
        "Postado": "2024-03-01",
        "autor": "Chu Dao",
        "artista": "Chu Dao",
        "nomes_alternativos": "Nuzi Xueyuan De Nansheng",
        "estado": "ativo",
        "genero": "Comedia, Ecchi, Escolar, Harem, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/U/um%20garoto%20na%20escola%20feminina/capitulo-",

        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/imgs/um%20garoto%20na%20escola%20feminina.jpg",
        "novo_capitulo": "",
        "historia": "Eu me chamo Qin Feng, 18 anos. Normalmente, eu puno o mal, promovo o bem, luto pela paz mundial, todos os dias ajudando vovós a atravessar a rua, ajudando crianças que perderam o caminho de casa, salvar donzelas perdidas, etc… Mas até que um dia, fui forçado a ir para a lendária Escola Feminina de Chongnan para estudar, assim tornando-se o único garoto da faculdade. Talvez aos olhos dos outros isto seja um paraíso, mas na realidade um futuro inimaginável vai…",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 3.5,
        "id": "L",
        "nome": "Living With a Kunoichi",
        "tipo": "manga",
        "num_capitulos": 8,
        "lancamento": "2022",
        "Postado": "2023-01-10",
        "autor": "Yuuya Hiiragi",
        "artista": "Yuuya Hiiragi",
        "nomes_alternativos": "Living with a Kunoichi Girl, My Roommate is a Kunoichi, The Kunoichi Lives Next Door, Doukyo wa Kunoichi desu, 同居人はくノ一です",
        "estado": "ativo",
        "genero": "Comedia, Demônios, Romance",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/L/Living%20With%20a%20Kunoichi/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Living%20With%20a%20Kunoichi.jpg",
        "novo_capitulo": "",
        "historia": "Tae, uma linda garota de 17 anos, e Kotaro, um sério trabalhador de escritório. Essas duas pessoas aparentemente felizes têm um segredo que não podem revelar a ninguém - os ninjas rivais de Iga e Kouga vivem secretamente juntos nesta comédia, romântica descontraída!",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 4.5,
        "id": "A",
        "nome": "A-Rank Boukensha no Slow Life",
        "tipo": "manga",
        "num_capitulos": 34,
        "lancamento": "2019",
        "Postado": "2022-01-10",
        "autor": "Kugeko Warabino (久賀京)",
        "artista": "Fumi Tadauri (田頭ふみ)",
        "nomes_alternativos": "Ａランク冒険者のスローライフ, An A-Ranked Adventurer’s “Slow-living”",
        "estado": "ativo",
        "genero": "Aventura, Fantasia, Magia, Romance, slice of life",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/A/A-Rank%20Boukensha%20no%20Slow%20Life/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/A-Rank%20Boukensha%20no%20Slow%20Life.jpg",
        "novo_capitulo": "",
        "historia": "O DragonSlayer Aldred é o aventureiro nº 1 de Rank-A e também o líder de um grupo de outros Rank-A do reino de Avalonia, que após cumprir a tarefa de eliminar um dragão decide desfazer o grupo. Para quem sempre buscou a força não querendo ser o melhor mas sim para poder sobreviver. Após conseguir o título de nº 1 e não precisar mais de dinheiro. Aldred decide viver sua vida e o lugar que escolheu, uma vila pequena que visitou a 9 anos durante uma de suas missões chamada de Nordende. Nodende é uma vila rural, cheia de belezas naturais e bem longe do reino de Avalonia que para Aldred seria perfeito onde ninguém saberia que ele é o Rank-A nº 1. Após desfazer o grupo. Aldred parte em sua viagem até Nordende, para poder viver uma vida confortável e relaxante e principalmente sem muitos problema",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 4.5,
        "id": "A",
        "nome": "Mushroom Brave",
        "tipo": "manhua",
        "num_capitulos": 56,
        "lancamento": "2021",
        "Postado": "2022-05-10",
        "autor": "Shibujun(拾部君)",
        "artista": "Shibujun(拾部君)",
        "nomes_alternativos": "Mushroom Hero, The Journey of a Mushroom to Be Overpowered in Another World, 蘑菇勇者",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comédia, Drama, Fantasia, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/M/Mushroom%20Brave/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/imgs/Mushroom%20Brave.jpg",
        "novo_capitulo": "",
        "historia": "Wazi, um jogador profissional, mas um estudante universitário comum, é convidado em um encontro por seu colega jogador. No entanto, ele é atropelado por um caminhão em seu caminho. Decidi mudar minha vida a partir de hoje... É assim que vai acabar...? Não, eu quero viver a vida dos meus sonhos... Onde eu estou...? O que é este lugar? Bem-vindo ao Brave Mainland! Estou me transformando em um Cogumelo? Como vou matar o rei demônio?! A história de um cogumelo covarde em suas aventura,s para se tornar um guerreiro poderoso.",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.5,
        "id": "T",
        "nome": "Tensei Shitara SSS-Kyuu Goblin ni NarimashitaMushroom Brave",
        "tipo": "manhwa",
        "num_capitulos": 20,
        "lancamento": "2023",
        "Postado": "2024-03-16",
        "autor": "Miki Kazuma",
        "artista": "CH Pocket",
        "nomes_alternativos": "I Reincarnated as an SSS-Ranked Goblin",
        "estado": "ativo",
        "genero": "Ação, Drama, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhwas/T/Tensei%20Shitara%20SSS-Kyuu%20Goblin%20ni%20Narimashita/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhwas/capas/Tensei%20Shitara%20SSS-Kyuu%20Goblin%20ni%20Narimashita.jpg",
        "novo_capitulo": "",
        "historia": 'Quando dei por mim, eu era um Goblin. Reencarnei em um monstro do ranque mais baixo em um jogo VRMMO de última geração,. Após perseverar na minha vida tumultuada como um goblin em conjunto com a minha irmã caçula, Lilly, eu fui morto durante uma invasão conduzida pelo herói. Por que tive que morrer dessa forma após ter acabado de reencarnar...? "...Não, você ainda não pode morrer." Prestes a morrer, eu fui trazido de volta à vida pela Deusa Goblin. Ela me reviveu porque queria que eu me tornasse o "Mais poderoso e inigualável Goblin". Ela me concedeu as habilidades: "Máximo Elemento Sombrio", "Habilidade de Conjurar todos os feitiços sombrios" e "Habilidade de Evocar todos os espíritos dos grandes Goblins do passado". Tipo, essas são habilidades do Ranque-SSS , não são?! O poder de destruir todos os demônios, de alto ranque que me discriminaram e todos os monstros gigantes que me trataram feito lixo. Eu darei uma surra no Lorde Demônio e no Herói e me tornarei o Messias Goblin!',
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.2,
        "id": "K",
        "nome": "Kusozako Choroin Nishiga Hachi",
        "tipo": "manga",
        "num_capitulos": 14,
        "lancamento": "2020",
        "Postado": "2024-03-16",
        "autor": "Kamatama",
        "artista": "Kamatama",
        "nomes_alternativos": "Kusozako Choroin Nishiga Hachi, A ingênua e desajeitada Nishiga Hachi, クソザコちょろイン西賀蜂 ",
        "estado": "ativo",
        "genero": "Comédia, Romance, slice of life",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/K/Kusozako%20Choroin%20Nishiga%20Hachi/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Kusozako%20Choroin%20Nishiga%20Hachi.jpg",
        "novo_capitulo": "",
        "historia": "Nishiga Hachi, uma kouhai feminina, quer fazer com que nosso protagonista, Azuma, se importe com ela, seguindo-o constantemente. Ela sempre tenta levar vantagem, mas por causa de sua lógica de merda e estupidez, ela sempre acaba em lágrimas depois que Azuma a ignora. Um Counter Rom-Com sobre uma heroína kouhai crédula e um protagonista super-seco!",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.2,
        "id": "R",
        "nome": "Ryoushin no Shakkin wo Katagawari shite morau Jouken wa Nihon Ichi Kawaii Joshikousei to Issho ni Kurasu koto deshita.",
        "tipo": "manga",
        "num_capitulos": 20,
        "lancamento": "2022",
        "Postado": "2024-03-16",
        "autor": "Amane Megumi",
        "artista": "Amane Megumi",
        "nomes_alternativos": " '両親の借金を肩代わりしてもらう条件は日本一可愛い女子校生と一緒に暮らすことでした。', '替我父母偿还债务的条件是与日本最可爱的女高中生同居。",
        "estado": "ativo",
        "genero": "Comédia, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/R/Ryoushin%20no%20Shakkin%20wo%20Katagawari%20shite%20morau%20Jouken%20wa%20Nihon%20Ichi%20Kawaii%20Joshikousei%20to%20Issho%20ni%20Kurasu%20koto%20deshita/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Ryoushin%20no%20Shakkin%20wo%20Katagawari%20shite%20morau%20Jouken.jpg",
        "novo_capitulo": "",
        "historia": "Yoshizumi Yuya, estava sendo pressionado à pagar a dívida deixada por seus pais que haviam fugido para o exterior. Foi sua colega de classe, Hitotsuba Kaede, escolhida como a colegial mais fofa do Japão, quem o salvou dessa crise de vida ou morte. No entando houve um problema. A condição em troca de assumir sua dívida era “- Em troca do empréstimo, você tem que viver comigo.” A comédia, romântica entre a bela, mas descontraída Hitotsuba Kaede e o sério e teimoso Yoshizumi Yuya, começa agora!",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.4,
        "id": "M",
        "nome": "Mezametara Saikyou Soubi to Uchuusen-mochi Datta no de, Ikkodate Mezashite Youhei Toshite Jiyuu ni Ikitai",
        "tipo": "manga",
        "num_capitulos":35,
        "lancamento": "2020",
        "Postado": "2021-03-16",
        "autor": "Ryuto",
        "artista": "MATSUI Shuinichi",
        "nomes_alternativos": "Reborn as a Space Mercenary: I Woke Up Piloting the Strongest Starship!, When I Woke Up, I Got the Strongest Equipment and a Spaceship, so I Went and Became a Mercenary in Order to Live as I Please While Aiming for a Detached House",
        "estado": "ativo",
        "genero": "Ação, Comédia, Drama, Ecchi, Harem, Romance, Sci-fi, Seinen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/M/Mezametara%20Saikyou%20Soubi%20to%20Uchuusen-mochi%20Datta%20no%20de%2C%20Ikkodate%20Mezashite%20Youhei%20Toshite%20Jiyuu%20ni%20Ikitai/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Mezametara%20Saikyou%20Soubi%20to%20Uchuusen-mochi%20Datta%20no%20de%2C%20Ikkodate%20Mezashite%20Youhei%20Toshite%20Jiyuu%20ni%20Ikitai.jpg",
        "novo_capitulo": "",
        "historia": "Sato Takahiro era um trabalhador de escritório comum e jogador amador até o dia em que acordou em uma nave espacial – uma que estranhamente se parecia com uma nave de um jogo de tiro espacial favorito. Com uma nave enfeitada, uma tripulação, cheia de garotas e um universo fantástico para explorar, ele vai aproveitar ao máximo sua boa sorte e criar a vida com que sempre sonhou!",
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.4,
        "id": "K",
        "nome": "Keikenzumi na Kimi to, Keiken Zero na Ore ga, Otsukiai suru Hanashi",
        "tipo": "manga",
        "num_capitulos":6,
        "lancamento": "2022",
        "Postado": "2023-02-16",
        "autor": "Nagaoka Makiko",
        "artista": "Carpaccio Noyama",
        "nomes_alternativos": "経験済みなキミと、 経験ゼロなオレが、 お付き合いする話。",
        "estado": "ativo",
        "genero": "Escolar, Romance, Shounen, slice of life",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/K/Keikenzumi%20na%20Kimi%20to%2C%20Keiken%20Zero%20na%20Ore%20ga%2C%20Otsukiai%20suru%20Hanashi/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Keikenzumi%20na%20Kimi%20to%2C%20Keiken%20Zero%20na%20Ore%20ga%2C%20Otsukiai%20suru%20Hanashi..jpg",
        "novo_capitulo": "",
        "historia": '“E-Eu gosto de você!” “Hãã? Susuki!?”. Kashima Ryuuto, estudante do médio sombrio. Por causa de um desafio, ele foi forçado a se confessar para Shirakawa Runa, uma garota do topo dos grupinhos da escola e admirada por todos. Eles acabaram em um relacionamento por uma inesperada resposta “Err, estou solteira agora, então” mas, Ryuuto acabou a seguindo e escutando um cara bonito do clube de futebol se confessando para Runa, e depois Runa levou Ryuuto, com quem acabou de começar a namorar, para seu próprio quarto como se fosse uma coisa natural. Eles tem amigos diferentes e jeitos diferentes de se divertir, diferentes em praticamente tudo. Ainda assim, surpresos pelas diferenças todos os dias, aceitando isso, eles começam a se relacionar.',
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.4,
        "id": "U",
        "nome": "Undead King ~Teihen Bouken-sha, Mamono no Chikara de Shinka Musou~",
        "tipo": "manga",
        "num_capitulos":25,
        "lancamento": "2023",
        "Postado": "2023-03-16",
        "autor": "Yuuji Hiiragi",
        "artista": "Shouta Satou",
        "nomes_alternativos": "Undead King ~A Low-Ranking Adventurer; With the Power of Monsters; Becomes Unbeatable~",
        "estado": "ativo",
        "genero": "Ação, Drama, Fantasia, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/U/Undead%20King%20%7ETeihen%20Bouken-sha%2C%20Mamono%20no%20Chikara%20de%20Shinka%20Musou%7E/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Undead%20King%20%7ETeihen%20Bouken-sha%2C%20Mamono%20no%20Chikara%20de%20Shinka%20Musou%7E.jpg",
        "novo_capitulo": "",
        "historia": '(Habilidades) um poder que os humanos só podem receber uma vez de deus, que é usado para lutar contra monstros. Chrome, que aspirava ser um aventureiro embora possuísse uma habilidade inútil em combate, não consegue jogar fora sua ambição e é desprezado por sua incapacidade, então fica encarregado de tarefas domésticas e tarefas de sua carreira. Mas, quando ele está fugindo de um monstro como uma isca, ele perde a vida. Mas naquele momento, sua habilidade é ativada. A habilidade (Renascimento). Por apenas uma vez, ele pode voltar dos mortos, e Chrome revive milagrosamente como um monstro esqueleto, um “Wight”. Chrome, que se desespera com seu novo corpo, descobre que conforme os monstros evoluem, sua aparência muda de acordo, então ele decide evoluir o mais rápido possível. Acreditando que pode recuperar sua aparência humana, Chrome passa seus dias caçando monstros. Como subproduto, o Chrome ganha uma infinidade de habilidades, enquanto um humano só pode ter uma ––! Poderosas habilidades de monstros e a inteligência de um humano. Superando adversidades com chance, Chrome mais uma vez pretende ser o aventureiro mais forte!',
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.4,
        "id": "M",
        "nome": "My Daughter Is the Final Boss",
        "tipo": "manhwa",
        "num_capitulos":86,
        "lancamento": "2022",
        "Postado": "2023-03-16",
        "autor": "RK Studio",
        "artista": "RK Studio",
        "nomes_alternativos": "My Daughter is the Final Boss",
        "estado": "ativo",
        "genero": "Ação, Aventura, Fantasia, Seinen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhwas/M/My%20Daughter%20Is%20the%20Final%20Boss/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhwas/capas/My%20Daughter%20Is%20the%20Final%20Boss.jpg",
        "novo_capitulo": "",
        "historia": 'Minha filha destruiu o mundo. No final da encruzilhada, morri desamparado. Quando abri os olhos novamente, vi minha filha de cinco anos na minha frente. Evite os cinco infortúnios de Seol-Ah Lee. (0/5) Chance dada mais uma vez. Se criada incorretamente, o mundo perecerá.',
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.5,
        "id": "C",
        "nome": "Contos de Demônios e Deuses",
        "tipo": "manhua",
        "num_capitulos":30,
        "lancamento": "2019",
        "Postado": "2021-03-16",
        "autor": "Mad Snail",
        "artista": "Jiang Ruotai",
        "nomes_alternativos": "Yao Shen Ji, Yêu Thần Ký, 妖神记, TDG, Tales of Demons and Gods",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comédia, Drama, Fantasia, Harem, Romance, Shounen",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/T/Tales%20of%20Demons%20and%20Gods/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/manhuas/imgs/Tales%20of%20Demons%20and%20Gods.jpg",
        "novo_capitulo": "",
        "historia": 'Nie Li, o mais poderoso Espiritualista Demoníaco e estando no topo do mundo marcial, perde sua vida durante a batalha com o Imperador Sábio e as seis bestas de nível divino, e sua alma volta ao passado para quando ele tinha 13 anos. Embora ele seja o mais fraco em sua classe, com o talento mais baixo no reino da alma Vermelho – o mais fraco dos reinos – com a ajuda de seu vasto conhecimento acumulado na sua vida passada, cresce mais rápido do que todos. Agora, ele irá tentar proteger a cidade que no futuro será invadida pelas bestas e que acabou sendo destruída, assim como sua amada, seus amigos e sua família que morreram pelo ataque das mesmas, e destruir a família Sagrada que abandonaram seus deveres e traíram a cidade em sua vida passada.',
        "CapituloInicia": 1,
    },
	{
        "key": "on",
        "nota": 5.5,
        "id": "I",
        "nome": "Isekai de Slow Life o (Ganbou)",
        "tipo": "manga",
        "num_capitulos":26,
        "lancamento": "2019",
        "Postado": "2020-03-16",
        "autor": "Shige",
        "artista": "Nagayori",
        "nomes_alternativos": "(想要）在异世界过慢生活, I Have a Slow Life Living in Different World (I Wish), I Have a Slow Living in Different World (I Wish), Isekai de Slow Life wo (Ganbou), Slow Life in Another World (I Wish!), 異世界でスローライフを(願望)",
        "estado": "ativo",
        "genero": "Ação, Aventura, Comédia, Drama, Ecchi, Fantasia, Harem, Maduro, Romance, Shounen, Slice of life",
        "pasta": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/I/Isekai%20de%20Slow%20Life%20o%20(Ganbou)/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/JoaoManga27/Quadrinhos/main/mangas/capas/Isekai%20de%20Slow%20Life%20o%20(Ganbou).jpg",
        "novo_capitulo": "",
        "historia": 'Pela vontade da deusa, Itsuki Shinomiya recebeu o privilégio de escolher várias habilidades e renascer em outro mundo. No entanto, antes de ir para o outro mundo, ele não queria se envolver em coisas assustadoras, sujas e grosseiras como batalhas. Ferozmente determinado a viver uma vida lenta, ele escolheu a habilidade única [Pocket Money], dando a ele uma quantia em dinheiro uma vez por dia. “Com isso, posso sair com as garotas sem precisar trabalhar!”. Sonhando em evitar batalhas e viver com lindas garotas, Itsuki entrou no outro mundo! Mas a realidade não era tão simples. Ser atacado por insetos gigantes, se envolver em discussões na guilda e ficar preso a escravos? No final, Itsuki será capaz de viver sua vida lenta ideal? Usando habilidades únicas e habilidades de fabricação, uma emocionante vida lenta de outro mundo com lindas garotas começa agora.',
        "CapituloInicia": 1,
    },
];

// localStorage.setItem('mangas-e-manhwas', JSON.stringify(mangas_e_manhwas))