let mangas_e_manhwas = [
    {
        "key": "of",
        "id": "F",
        "nome": "Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!)",
        "text_cap": "Capitulos: ",
        "lancamento": "2022",
        "tipo": "manhwa",
        "num_capitulos": 106,
        "estado": "completo",
        "genero": "Fantasia, Histórico, Josei, Romance, Shoujo, Sobrenatural",
        "pasta": "Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!)",
        "caminho-img": "./imgs/Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!).jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "H",
        "nome": "Hougong Tai Duo, Zhihao Feishengle - My Harem Grew So Large, I Was Forced to Ascend",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Artes Marciais Aventura Fantasia Harem Isekai Romance Webtoon acao",
        "pasta": "",
        "caminho-img": "./imgs/Hougong Tai Duo, Zhihao Feishengle - My Harem Grew So Large, I Was Forced to Ascend.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 3.5,
        "id": "I",
        "nome": "Isekai Cheat Magician",
        "tipo": "manga",
        "num_capitulos": 15,
        "lancamento" : "2017",
        "Postado" : "2023-02-25",
        "autor" : "Takeru Uchida",
        "artista" : "Nardack",
        "nomes_alternativos" : "Isekai Cheat Majutsushi, 異世界チート魔術師",
        "estado": "ativo",
        "genero": "Aventura Ação Fantasia Isekai Romance Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I/Isekai%20Cheat%20Magician/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Isekai%20Cheat%20Magician.jpg",
        "novo_capitulo" : "",
        "historia" : "Dois alunos normais do ensino médio, Taichi e Rin, desaparecem em um feixe de luz. Quando perceberam, eles já estavam em um mundo de espadas e magia. Finalmente, depois de experimentar um ataque de monstros, e seguindo a sugestão de aventureiros, eles seguiram o caminho para entrar em uma guilda. Nessa guilda, os dois descobrem que possuem magia incrivelmente poderosa. Assim, os alunos regulares do ensino médio transformaram-se nos cheaters mais fortes.",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "J",
        "nome": "It's Time to Change the Genre",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Fantasia, Isekai, Reencarnação, Romance, Shoujo",
        "pasta": "It’s Time to Change the Genre",
        "caminho-img": "./imgs/Jangleuleul Bakkwobodolog Hagessseubnida - It's Time to Change the Genre.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "R",
        "nome": "Rebirth of the Divine Doctor",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "estado": "ativo",
        "genero": "acao Artes Marciais Aventura Comédia Fantasia Histórico Isekai Manhua Medicina Reencarnação",
        "pasta": "",
        "caminho-img": "./imgs/Rebirth of the Divine Doctor.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "Taming the Lady",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "acao Fantasia Isekai Manhwa Shoujo Webtoon",
        "pasta": "",
        "caminho-img": "./imgs/Taming the Lady.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "The Lady Wants to Rest",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Isekai Manhwa Romance Shoujo Webtoon",
        "pasta": "",
        "caminho-img": "./imgs/The Lady Wants to Rest.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "W",
        "nome": "Wo Shi Yì Shijie Zui Qiang Lingzhu - I Am the Strongest Lord in Another World",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Wo Shi Yì Shijie Zui Qiang Lingzhu - I Am the Strongest Lord in Another World.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bokutachi wa Hanshoku wo Yameta",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Bokutachi wa Hanshoku wo Yameta.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "Tensei shitara Slime Datta Ken Mamono no Kuni no Arukikata",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Tensei shitara Slime Datta Ken Mamono no Kuni no Arukikata.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "Tensei Shitara Ore ga Heroine de Aitsu ga Yuusha Datta",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Tensei Shitara Ore ga Heroine de Aitsu ga Yuusha Datta.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Sensei Wa Koi Wo Oshie Rarenai",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Sensei Wa Koi Wo Oshie Rarenai.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "L",
        "nome": "Lv2 kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life",
        "tipo": "manga",
        "num_capitulos": 50,
        "lancamento" : "2019",
        "Postado" : "2022-02-26",
        "autor" : "KINOJO Miya",
        "artista" : "ITOMACHI Akine",
        "nomes_alternativos" : "Candidate was a Cheat from Lv2, Chillin Different World Life of the Ex-Brave Candidate was Cheat from Lv2, LV2からチートだった元勇者候補のまったり異世界ライフ",
        "estado": "ativo",
        "genero": "Ação Aventura Comedia Fantasia Romance Shounen Slice-of-Life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/L/Lv2%20kara%20Cheat%20datta%20Motoyuusha%20Kouho%20no%20Mattari%20Isekai%20Life/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Lv2 kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life.jpg",
        "novo_capitulo" : "",
        "historia" : "Um protagonista renascido em outro mundo. Aparentemente ele havia reencarnado como um filho abandonado, junto a outros órfãos. Para sobreviver, ele os conduziu à agricultura. Pouco a pouco, os órfãos se reuniram, e ao ouvir rumores de uma aldeia, outros começaram a migrar. O grupo que tinha sido nada além de crianças tornou-se uma aldeia antes que alguém percebesse. E então, vários países nos arredores começaram a observá-lo... Este é o conto épico do homem que mais tarde seria conhecido como o Imperador Divino.",
        "CapituloInicia" : 1,
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "I",
        "nome": "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken",
        "tipo": "manga",
        "num_capitulos": 14,
        "lancamento" : 2019,
        "Postado" : "2024-02-26",
        "autor" : "Saeki-san",
        "artista" : "KAZUTAKE Hazano",
        "nomes_alternativos" : "The Angel Next Door Spoils Me Rotten, お隣の天使様にいつの間にか駄目人間にされていた件",
        "estado": "ativo",
        "genero": "Comedia Romance Shounen fantasia",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/O/Otonari%20no%20Tenshi-sama%20ni%20Itsunomanika%20Dame%20Ningen%20ni%20Sareteita%20Ken/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Otonari%20no%20Tenshi-sama%20ni%20Itsunomanika%20Dame%20Ningen%20ni%20Sareteita%20Ken.jpg",
        "novo_capitulo" : "",
        "historia" : "Amane mora sozinho em um apartamento, e a garota mais bonita da escola, Mahiru, mora bem ao lado. Eles quase nunca se falam – até o dia em que ele a vê em apuros em um dia chuvoso e empresta seu guarda-chuva a ela. Para retribuir o favor, ela oferece a ele ajuda na casa, e um relacionamento começa a florescer lentamente à medida que a distância entre eles diminui…",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "K",
        "nome": "Kuro no Shoukanshi",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Kuro no Shoukanshi.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "L",
        "nome": "Love Comedy Manga ni Haitteshimatta node, Oshi no Make Heroine wo Zenryoku de Shiawase ni Suru",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Love Comedy Manga ni Haitteshimatta node, Oshi no Make Heroine wo Zenryoku de Shiawase ni Suru",
        "caminho-img": "./imgs/Love Comedy Manga ni Haitteshimatta node, Oshi no Make Heroine wo Zenryoku de Shiawase ni Suru.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "I",
        "nome": "Isekai De Tochi O Katte Noujou O Tsukurou",
        "tipo": "manga",
        "num_capitulos": 31,
        "lancamento" : "2019",
        "Postado" : "2023-04-26",
        "autor" : "OKAZAWA Rokujuuyon",
        "artista" : "SASAMEYUKI Jun",
        "nomes_alternativos" : "Isekai de Tochi o Katte Noujou o Tsukurou, Let's Buy the Land and Cultivate in Different World, 在异世界购买土地建造农场, 異世界で土地を買って農場を作ろう",
        "estado": "ativo",
        "genero": "Ação Aventura Comedia Ecchi Fantasia Harem Romance Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I/Isekai%20De%20Tochi%20O%20Katte%20Noujou%20O%20Tsukurou/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Isekai%20De%20Tochi%20O%20Katte%20Noujou%20O%20Tsukurou.jpg",
        "novo_capitulo" : "",
        "historia" : "Como nosso humilde corporativista Itonami Norio é repentinamente convocado para outro mundo, pareceria que ele seria enviado para um campo de batalha – ele, entretanto, não possui nenhuma habilidade para falar, e como ele é considerado inútil. Ele negocia com o rei e recebe um terreno – um terreno vazio e deserto, sem nenhum habitante à vista. Norio segura algo que ele não poderia contar a ninguém: O Mestre da Supremacia, um presente que lhe dará a mais confortável das vidas neste mundo. Aqui começa a colorida história de Norio – tendo uma sereia que ele pesca se declara sua esposa, tornando-se vizinha do Rei Morto-vivo, esta é sua vida ocupada, mas divertida – e agora um dragão aparece?!",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?",
        "tipo": "manga",
        "pasta": "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "I",
        "nome": "Isekai Kenkokuki",
        "tipo": "manga",
        "num_capitulos": 61,
        "lancamento" : "2017",
        "Postado" : "2022-05-01",
        "autor" : "Sakuragi, Sakura",
        "artista" : "KOIZUMI",
        "nomes_alternativos" : "Different World Foundation, Otherworld Nation Founding Chronicles, Isekai Kenkoku-ki",
        "estado": "ativo",
        "genero": "Ação Drama Aventura Fantasia Harem Isekai Romance Slice-Of-Life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/I/Isekai%20Kenkokuki/capitulo-",
        "caminho-img": "https://github.com/oclubedosdez/Imagens/blob/main/mangas/img/Isekai%20Kenkokuki.jpg?raw=true./imgs/Isekai Kenkokuki.jpg",
        "novo_capitulo" : "",
        "historia" : "Um protagonista renascido em outro mundo. Aparentemente ele havia reencarnado como um filho abandonado, junto a outros órfãos. Para sobreviver, ele os conduziu à agricultura. Pouco a pouco, os órfãos se reuniram, e ao ouvir rumores de uma aldeia, outros começaram a migrar. O grupo que tinha sido nada além de crianças tornou-se uma aldeia antes que alguém percebesse. E então, vários países nos arredores começaram a observá-lo... Este é o conto épico do homem que mais tarde seria conhecido como o Imperador Divino.",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "R",
        "nome": "Release That Witch",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "",
        "caminho-img": "./imgs/Release That Witch.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Survive On A Deserted Island With Beautiful Girls",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Survive On A Deserted Island With Beautiful Girls",
        "caminho-img": "./imgs/Survive On A Deserted Island With Beautiful Girls.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Fate/stay night",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Fate stay night",
        "caminho-img": "./imgs/Fate stay night-14.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "Isekai Yurutto Survival Seikatsu: Gakkou no Minna to Isekai no Mujintou ni Tenishitakedo Ore Dake Rakushou desu",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "",
        "pasta": "Isekai Yurutto Survival Seikatsu Gakkou no Minna to Isekai no Mujintou ni Tenishitakedo Ore Dake Rakushou desu",
        "caminho-img": "./imgs/Isekai Yurutto Survival Seikatsu Gakkou no Minna to Isekai no Mujintou ni Tenishitakedo Ore Dake Rakushou desu.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Martial God Asura",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Artes Marciais Aventura Ação Harem Romance Seinen Sobrenatural",
        "pasta": "Martial God Asura",
        "caminho-img": "./imgs/Martial God Asura.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Tales of Demons and Gods",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Artes_Marciais Aventura Ação Fantasia Isekai Romance Seinen",
        "pasta": "Tales of Demons and Gods",
        "caminho-img": "./imgs/Tales of Demons and Gods.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Amazing Wechat",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Aventura, Ação, Ecchi, Escolar, Fantasia, Manhua, Shounen, Slice of Life, Webtoon",
        "pasta": "My Amazing Wechat",
        "caminho-img": "./imgs/My Amazing Wechat.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Villainous Master Brings Along the Peerless Apprentices",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Ação Artes Marciais Drama Fantasia Shounen",
        "pasta": "My Villainous Master Brings Along the Peerless Apprentices",
        "caminho-img": "./imgs/My Villainous Master Brings Along the Peerless Apprentices.webp",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 5.2,
        "id": "E",
        "nome": "Eu tive um filho do tirano",
        "tipo": "manhwa",
        "num_capitulos": 105,
        "lancamento" : "2023",
        "Postado" : "2022-02-26",
        "autor" : "Ryuran,SF_JD",
        "artista" : "SF_JD",
        "nomes_alternativos" : "폭군의 아이를 가졌습니다, I Got Pregnant to the Tyrant’s Child",
        "estado": "completo",
        "genero": "Drama fantasia Historico Josei Romance",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/E/Eu%20tive%20um%20filho%20do%20tirano/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Eu%20tive%20um%20filho%20do%20tirano.jpg",
        "novo_capitulo" : "",
        "historia" : "Para Elan, o cavaleiro real, o festival de máscaras é uma rara chance de se soltar e relaxar. Mas sua noite de diversão rapidamente se transforma em uma manhã de horror quando ela acorda ao lado do implacável imperador Kylart. Sabendo o quão cruel ele pode ser com mulheres pegajosas, Elan foge, esperando que ele não tenha visto além de seu disfarce. Mas enquanto ela continua seus deveres estressantes de guardar o imperador, ela começa a sentir sintomas preocupantes de saúde. Uma ida ao médico revela que ela está grávida! Para piorar as coisas, há rumores de que Kylart está procurando a misteriosa mulher que conheceu na noite do festival. Elan pode manter seu segredo a salvo de todo o palácio, quando ela nem consegue controlar seus desejos constantes e enjôos matinais?</span>",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bloody Kiss (Yagami Rina)",
        "tipo": "manga",
        "status": "completo",
        "num_capitulos": "",
        "estado": "finalizado",
        "genero": "Romance Shoujo Sobrenatural",
        "pasta": "Bloody Kiss (Yagami Rina)",
        "caminho-img": "./imgs/Bloody Kiss (Yagami Rina).jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bloody Kiss",
        "tipo": "manga",
        "status": "completo",
        "num_capitulos": "",
        "estado": "finalizado",
        "genero": "Romance Shoujo Sobrenatural",
        "pasta": "Bloody Kiss",
        "caminho-img": "./imgs/Bloody Kiss.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bara to Juudan",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "completo",
        "genero": "Fantasia Romance Shoujo Sobrenatural Vida_Escolar",
        "pasta": "Bara to Juudan",
        "caminho-img": "./imgs/Bara to Juudan.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Ai Hime ~ Ai to Himegoto",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "completo completo2",
        "genero": "Drama Romance Shoujo",
        "pasta": "Ai Hime ~ Ai to Himegoto",
        "caminho-img": "./imgs/Ai Hime ~ Ai to Himegoto.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bishounen No Oheya",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "completo",
        "genero": "Comédia Harem Romance Shoujo Vida_Escolar",
        "pasta": "Bishounen No Oheya",
        "caminho-img": "./imgs/Bishounen No Oheya.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "Z",
        "nome": "Zatsuyou Fuyo Jutsushi ga Jibun no Saikyou ni Kizuku made",
        "tipo": "manga",
        "num_capitulos": 17,
        "estado": "ativo",
        "genero": "Ação Fantasia Shounen",
        "pasta": "Zatsuyou Fuyo Jutsushi ga Jibun no Saikyou ni Kizuku made",
        "caminho-img": "./imgs/Zatsuyou Fuyo Jutsushi ga Jibun no Saikyou ni Kizuku made.jpg",
        "novo_capitulo" : "novo",
    },
    {
        "key": "of",
        "id": "O",
        "nome": "Otherworldly Magical Daoist Priest",
        "tipo": "manhwa",
        "num_capitulos": 40,
        "estado": "ativo",
        "genero": "Ação, Artes Marciais, Comédia, Drama, Fantasia, Isekai, Magia, Shounen",
        "pasta": "Otherworldly Magical Daoist Priest",
        "caminho-img": "./imgs/Otherworldly Magical Daoist Priest.jpg",
        "novo_capitulo" : "novo",
    },
    {
        "key": "of",
        "id": "O",
        "nome": "I’m in Trouble Because My Husband Is So Cute",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Ação, Aventura, Drama, Fantasia, Histórico, Josei, Romance, Seinen",
        "pasta": "I’m in Trouble Because My Husband Is So Cute",
        "caminho-img": "./imgs/I’m in Trouble Because My Husband Is So Cute.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "S",
        "nome": "Saenai Riman to Yankee Joshi Kousei",
        "tipo": "manga",
        "num_capitulos": 28,
        "lancamento" : "2021",
        "Postado" : "2023-02-22",
        "autor" : "Tamaki Nao",
        "artista" : "Tamaki Nao",
        "nomes_alternativos" : "Business-Geek e Highschool-Punk, 冴えないリーマンとヤンキー女子高生",
        "estado": "ativo",
        "genero": "Comedia Romance Slice-of-Life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/S/Saenai%20Riman%20to%20Yankee%20Joshi%20Kousei/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Saenai%20Riman%20to%20Yankee%20Joshi%20Kousei.jpg",
        "novo_capitulo" : "",
        "historia" : "Yamada Hiroyuki tem 26 anos, tem um emprego estável, é um otaku, oprimido pelas ideias e pensamentos de sua família (quando você se casa? Você ainda assiste animes na sua idade?) Ele decide sair de casa e ir morar em um apartamento, sozinho e feliz, mas a imagem perfeita que ele tinha em mente quando se mudou, foi destruída quando soube que sua vizinha é uma yankee (delinquente) e ao mesmo tempo uma colegial, logo ele descobre que aquela garota rude e desbocada é alguém desajeitada, muito terna e muito fofa. A história desses dois jovens avançará para melhor?",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "W",
        "nome": "Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago",
        "tipo": "manhwa",
        "num_capitulos": 23,
        "estado": "ativo",
        "lancamento" : "2022",
        "genero": "Drama Fantasia Romance Shounen Sobrenatural",
        "pasta": "Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago",
        "caminho-img": "./imgs/Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "Estou Tentando Me Divorciar do Meu Esposo Vilão, Mas Teremos Um Filho",
        "tipo": "manhwa",
        "num_capitulos": 85,
        "lancamento" : "2022",
        "estado": "ativo",
        "genero": "Drama Fantasia Josei Romance",
        "pasta": "Estou Tentando Me Divorciar do Meu Esposo Vilão, Mas Teremos Um Filho",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Estou%20Tentando%20Me%20Divorciar%20do%20Meu%20Esposo%20Vil%C3%A3o%2C%20Mas%20Teremos%20Um%20Filho.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Childhood Friend Became an Obsessive Male Lead",
        "tipo": "manhwa",
        "num_capitulos": 46,
        "text_cap" : "Capitulos: ",
        "lancamento" : "2022",
        "estado": "ativo",
        "genero": "Drama Fantasia Josei Romance",
        "pasta": "My Childhood Friend Became an Obsessive Male Lead",
        "caminho-img": "./imgs/My Childhood Friend Became an Obsessive Male Lead.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "A Proprietária Bebê Está se Aposentando",
        "num_capitulos": 120,
        "tipo": "manhwa",
        "text_cap" : "Capitulos: ",
        "estado": "ativo",
        "lancamento" : "2022",
        "genero": "Fantasia Romance Shoujo",
        "pasta": "A Proprietária Bebê Está se Aposentando",
        "caminho-img": "./imgs/A Proprietária Bebê Está se Aposentando.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "My Three Tyrant Brothers",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Drama Histórico Magia Romance Shoujo Sobrenatural",
        "pasta": "My Three Tyrant Brothers",
        "caminho-img": "./imgs/My Three Tyrant Brothers.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "K",
        "nome": "Knight of the Frozen Flower",
        "tipo": "manhwa",
        "num_capitulos": 52,
        "lancamento" : "2022",
        "estado": "ativo",
        "genero": "Acao Aventura Drama Fantasia Historico Psicologico Romance Shoujo",
        "pasta": "Knight of the Frozen Flower",
        "caminho-img": "./imgs/Knight of the Frozen Flower.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "D",
        "nome": "De Tantas Coisas, Me Tornei um Corvo",
        "tipo": "manhwa",
        "num_capitulos": 87,
        "lancamento" : "2022",
        "estado": "ativo",
        "genero": "Fantasia Romance Shoujo Sobrenatural",
        "pasta": "De Tantas Coisas, Me Tornei um Corvo",
        "caminho-img": "./imgs/De Tantas Coisas, Me Tornei um Corvo.jpeg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "N",
        "nome": "Nihon e Youkoso Elf-san",
        "tipo": "manga",
        "num_capitulos": 40,
        "lancamento" : "2018",
        "Postado" : "2022-02-22",
        "autor" : "Makishima Suzuki",
        "artista" : "Shimo Aono",
        "nomes_alternativos" : "Welcome to Japan, Elf-san",
        "estado": "ativo",
        "genero": "Aventura Comédia Ecchi Fantasia Romance Shounen Slice-of-Life",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/N/Nihon%20e%20Youkoso%20elf-san/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Nihon%20e%20Youkoso%20elf-san.jpg",
        "novo_capitulo" : "",
        "historia" : "Kitase Kazuhiro é um assalariado comum que sempre deixa o escritório na hora certa. Embora este seja o Japão, talvez ele não seja realmente comum, afinal. O que é verdadeiramente estranho vem depois disso; Toda noite, ele toma banho, troca seu pijama e tem uma boa noite de sono, em seguida, ele sonha com um mundo de fantasia, e só acorda quando ele morre ou dorme nesse mundo. Um dia, ele morreu depois de tropeçar no covil de um dragão. Nisso ele tem “Um pesadelo”, ele fica amuado, até que ele encontra sua amiga elfo em sua cama. Curioso para ver um elfo waifu experimentar a vida cotidiana no Japão? Como é andar com a fantasia de todo homem nas ruas de Tóquio? Este mangá é para todos vocês amantes de elfos por aí!",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "A",
        "nome": "A 99° Noiva do Duque",
        "tipo": "manhwa",
        "num_capitulos": 53,
        "lancamento" : "2022",
        "estado": "ativo",
        "genero": "Fantasia Romance Shoujo",
        "pasta": "A 99° Noiva do Duque",
        "caminho-img": "./imgs/A 99° Noiva do Duque.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "Fairy, Wait a Moment! Please Listen to My Argument",
        "tipo": "manhua",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Acao Aventura Drama Fantasia Shounen",
        "pasta": "Fairy, Wait a Moment! Please Listen to My Argument",
        "caminho-img": "./imgs/Fairy, Wait a Moment! Please Listen to My Argument.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bon Appétit!",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Drama Romance Shoujo",
        "pasta": "Bon Appétit!",
        "caminho-img": "./imgs/Bon Appétit!.jpeg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Ano Oni Kyoushi ga Boku no Ane ni Narundesuka",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Comédia Ecchi Escolar Romance Shounen Slice-of-Life",
        "pasta": "Ano Oni Kyoushi ga Boku no Ane ni Narundesuka",
        "caminho-img": "./imgs/Ano Oni Kyoushi ga Boku no Ane ni Narundesuka.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "I’m Not a Demon",
        "tipo": "manhua",
        "num_capitulos": 19,
        "lancamento" : "2023",
        "estado": "ativo",
        "genero": "Acao Aventura Drama Fantasia Shounen",
        "pasta": "I’m Not a Demon",
        "caminho-img": "./imgs/I’m Not a Demon.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "K",
        "nome": "Kekkon Yubiwa Monogatari",
        "tipo": "manga",
        "num_capitulos": 62,
        "lancamento" : "2016",
        "estado": "ativo",
        "genero": "Acao Ecchi Fantasia Harem Magia Romance Seinen",
        "pasta": "Kekkon Yubiwa Monogatari",
        "caminho-img": "./imgs/Kekkon Yubiwa Monogatari.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "id": "B",
        "nome": "Beware of the Brothers!",
        "tipo": "manhwa",
        "num_capitulos": 90,
        "lancamento" : "2020",
        "estado": "ativo",
        "genero": "Drama Fantasia Historico Romance Shoujo",
        "pasta": "Beware of the Brothers!",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhaws/imgs/Beware%20of%20the%20Brothers!.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Atenciosamente: Me Tornei a Empregada do Duque",
        "tipo": "manhwa",
        "status": "completo",
        "num_capitulos": "",
        "estado": "completo",
        "genero": "Fantasy Isekai Romance Shoujo",
        "pasta": "Atenciosamente Me Tornei a Empregada do Duque",
        "caminho-img": "./imgs/Atenciosamente Me Tornei a Empregada do Duque.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "C",
        "nome": "Circunstâncias da Irene",
        "tipo": "manhwa",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Drama Fantasia Josei Romance",
        "pasta": "Circunstâncias da Irene",
        "caminho-img": "./imgs/Circunstâncias da Irene.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "K",
        "nome": "Fuufu Ijou, Koibito Miman",
        "tipo": "manga",
        "num_capitulos": 65,
        "lancamento" : "2020",
        "estado": "ativo",
        "genero": "Comedia Drama Escolar Romance Slice-of-Life",
        "pasta": "Fuufu Ijou, Koibito Miman",
        "caminho-img": "./imgs/Fuufu Ijou, Koibito Miman.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "K",
        "nome": "kikan shita yuusha no gojitsudan",
        "tipo": "manga",
        "num_capitulos": "",
        "estado": "ativo",
        "genero": "Comédia Ecchi Fantasia Harem Romance Magia Shounen Isekai",
        "pasta": "kikan shita yuusha no gojitsudan",
        "caminho-img": "./imgs/kikan shita yuusha no gojitsudan.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "I Confessed to the Boss",
        "tipo": "manhwa",
        "num_capitulos": 59,
        "lancamento" : "2021",
        "estado": "ativo",
        "genero": "Comedia Drama Josei Romance Shoujo",
        "pasta": "I Confessed to the Boss",
        "caminho-img": "./imgs/I Confessed to the Boss.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "P",
        "nome": "Pretendente Surpresa",
        "tipo": "manhwa",
        "status": "completo",
        "num_capitulos": 124,
        "lancamento" : "2020",
        "estado": "completo",
        "genero": "Comedia Drama Josei Romance Slice-of-Life",
        "pasta": "Pretendente Surpresa",
        "caminho-img": "./imgs/Pretendente Surpresa.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "Q",
        "nome": "Quando a Filha Ilegítima do Conde se Casa",
        "tipo": "manhwa",
        "num_capitulos": 79,
        "lancamento" : "2022",
        "estado": "ativo",
        "genero": "Comédia Drama Josei Romance Slice-of-Life",
        "pasta": "Quando a Filha Ilegítima do Conde se Casa",
        "caminho-img": "./imgs/Quando a Filha Ilegítima do Conde se Casa.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Adelaide",
        "tipo": "manhwa",
        "status": "completo",
        "num_capitulos": 85,
        "lancamento" : "2017",
        "estado": "completo",
        "genero": "Fantasia Histórico Isekai Romance",
        "pasta": "Adelaide",
        "caminho-img": "./imgs/Adelaide.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "A protagonista feminina está tentando me tornar sua madrasta",
        "tipo": "manhwa",
        "num_capitulos": 41,
        "lancamento" : "2021",
        "estado": "ativo",
        "genero": "Fantasia Histórico Josei Romance Shoujo",
        "pasta": "A protagonista feminina está tentando me tornar sua madrasta",
        "caminho-img": "./imgs/A protagonista feminina está tentando me tornar sua madrasta.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "A",
        "nome": "A Relação Simbiótica Entre uma Coelha e Uma Pantera Negra",
        "tipo": "manhwa",
        "num_capitulos": 125,
        "lancamento" : "2021",
        "estado": "ativo",
        "genero": "Aventura Comedia Drama Fantasia Romance Shoujo Sobrenatural",
        "pasta": "A Relação Simbiótica Entre uma Coelha e Uma Pantera Negra",
        "caminho-img": "./imgs/A Relação Simbiótica Entre uma Coelha e Uma Pantera Negra.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "I",
        "nome": "I Time-Traveled and Confessed to My Teacher Crush",
        "tipo": "manga",
        "status": "completo",
        "num_capitulos": 55,
        "lancamento" : "2019",
        "estado": "completo",
        "genero": "Slice-of-life Romance Comedia Escolar Viagem-no-tempo",
        "pasta": "I Time-Traveled and Confessed to My Teacher Crush",
        "caminho-img": "./imgs/I Time-Traveled and Confessed to My Teacher Crush.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "E",
        "nome": "Eu Domei o Protagonista Masculino Que Tentou me Matar",
        "tipo": "manhwa",
        "num_capitulos": 25,
        "lancamento" : "2023",
        "estado": "ativo",
        "genero": "Drama Fantasia Romance Shoujo",
        "pasta": "Eu Domei o Protagonista Masculino Que Tentou me Matar",
        "caminho-img": "./imgs/Eu Domei o Protagonista Masculino Que Tentou me Matar.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Salvos A Monster Evolution LitRPG",
        "tipo": "manhwa",
        "num_capitulos": 35,
        "lancamento" : "2023",
        "estado": "ativo",
        "genero": "Acao Aventura Comedia Drama Fantasia Jogo Shounen",
        "pasta": "Salvos Uma evolução de monstro LitRPG",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/pages/manhwas/imgs/Salvos A Monster Evolution LitRPG.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Musume ja Nakute Mama ga Suki nano",
        "tipo": "manga",
        "num_capitulos": 30,
        "lancamento" : "2020",
        "estado": "ativo",
        "genero": "Comedia Romance",
        "pasta": "Musume ja Nakute Mama ga Suki nano",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Musume ja Nakute Mama ga Suki nano.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "S",
        "nome": "Saint Seiya Meiou Iden Dark Wing",
        "tipo": "manga",
        "num_capitulos": 29,
        "lancamento" : "2020",
        "Postado" : "2023-03-22",
        "autor" : "Masami Kurumada . Kenji Saito",
        "artista" : "Nobufune Ueda",
        "nomes_alternativos" : "聖闘士星矢 冥王異伝ダークウイング",
        "estado": "ativo",
        "genero": "Ação Aventura Fantasia Shounen Sobrenatural",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/Saint%20Seiya%20Meiou%20Iden%20Dark%20Wing/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Saint Seiya Meiou Iden Dark Wing.jpg",
        "novo_capitulo" : "",
        "historia" : "Um estudante do ensino médio sofre um acidente e acorda no Elíseo do Mundo dos Mortos. Em busca de respostas, ele se encontra com Hades, o Deus do Submundo.",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "C",
        "nome": "Congelamento Global",
        "tipo": "manhua",
        "num_capitulos": 7,
        "lancamento" : "2023",
        "estado": "ativo",
        "genero": "Acao Aventura Romance Sobrevivência",
        "pasta": "Congelamento Global",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/manhuas/img/Congelamento Global.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "T",
        "nome": "Tanbo de Hirotta Onna Kishi, Inaka de Ore no Yome dato Omowareteiru",
        "tipo": "manga",
        "num_capitulos": 10,
        "lancamento" : "2023",
        "estado": "ativo",
        "genero": "Fantasia Romance Shounen Slice-of-Life",
        "pasta": "Tanbo de Hirotta Onna Kishi, Inaka de Ore no Yome dato Omowareteiru",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Tanbo de Hirotta Onna Kishi, Inaka de Ore no Yome dato Omowareteiru.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "E",
        "nome": "Eternamente Level 1 Até A Morte",
        "tipo": "manga",
        "num_capitulos": 30,
        "lancamento" : "2021",
        "estado": "ativo",
        "genero": "Acao Aventura Fantasia Harem Romance Isekai Magia",
        "pasta": "Eternamente Level 1 Até A Morte",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Eternamente Level 1 Até A Morte.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "M",
        "nome": "Mushoku no Eiyuu: Betsu ni Skill Nanka Iranakattan daga",
        "tipo": "manga",
        "num_capitulos": 19,
        "lancamento" : "2018",
        "estado": "ativo",
        "genero": "Acao Aventura Comedia Fantasia Shounen",
        "pasta": "Mushoku no Eiyuu Betsu ni Skill Nanka Iranakattan daga",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Mushoku no Eiyuu Betsu ni Skill Nanka Iranakattan daga.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "S",
        "nome": "Shinigami ni Sodaterareta Shoujo wa Shikkoku no Tsurugi wo Mune ni Idaku",
        "tipo": "manga",
        "num_capitulos": 17,
        "lancamento" : "2019",
        "estado": "ativo",
        "genero": "Acao Aventura Fantasia Misterio Romance Seinen Sobrenatural",
        "pasta": "Shinigami ni Sodaterareta Shoujo wa Shikkoku no Tsurugi wo Mune ni Idaku",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Shinigami%20ni%20Sodaterareta%20Shoujo%20wa%20Shikkoku%20no%20Tsurugi%20wo%20Mune%20ni%20Idaku.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "of",
        "id": "B",
        "nome": "Bannou “Murazukuri” Cheat de Otegaru Slow Life ~Mura desu ga Nani ka?~",
        "tipo": "manga",
        "num_capitulos": 5,
        "lancamento" : "2023",
        "estado": "ativo",
        "genero": "Acao Aventura Comedia Fantasia Romance Shounen",
        "pasta": "Bannou “Murazukuri” Cheat de Otegaru Slow Life ~Mura desu ga Nani ka~",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Bannou%20%E2%80%9CMurazukuri%E2%80%9D%20Cheat%20de%20Otegaru%20Slow%20Life%20%7EMura%20desu%20ga%20Nani%20ka%7E.jpg",
        "novo_capitulo" : "",
    },
    {
        "key": "on",
        "nota" : 4.5,
        "id": "L",
        "nome": "Lilia’s Pregnancy Spells the World’s End",
        "tipo": "manga",
        "num_capitulos": 3,
        "lancamento" : 2023,
        "Postado" : "2024-02-25",
        "autor" : "Sakayama Shinta",
        "artista" : "Sakayama Shinta",
        "nomes_alternativos" : "Lilia Pregant The Word End, リリア・プレグナント・ザ・ワールド・エンド",
        "estado": "ativo",
        "genero": "Comedia Ecchi Fantasia Romance Shounen",
        "pasta": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/L/Lilia's%20Pregnancy%20Spells%20the%20World's%20End/capitulo-",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Lilia%E2%80%99s%20Pregnancy%20Spells%20the%20World%E2%80%99s%20End.jpg",
        "novo_capitulo" : "",
        "historia" : "O mundo será destruído se você fizer sexo com a filha do Rei Demônio.” Depois de derrotar o Rei Demônio e salvar o outro mundo, o herói Takahiro retorna ao mundo real. Um dia, Lilia, filha do Rei Demônio, chega de repente na casa de Takahiro, onde ele leva uma vida tranquila. Takahiro se prepara para a vingança, mas o objetivo dela é gerar um filho do forte do Takahiro…!?",
        "CapituloInicia" : 1,
    },
    {
        "key": "of",
        "id": "A",
        "nome": "Atsumori-kun no Oyome-san",
        "tipo": "manga",
        "num_capitulos": 16,
        "lancamento" : "2018",
        "estado": "ativo",
        "genero": "Comedia Drama Romance Shoujo Slice-of-Life",
        "pasta": "Atsumori-kun no Oyome-san",
        "caminho-img": "https://raw.githubusercontent.com/oclubedosdez/Imagens/main/mangas/img/Atsumori-kun%20no%20Oyome-san.jpg",
        "novo_capitulo" : "",
    },
];