var sele = document.getElementById("selecionar")


    let select_element = `
        <option value="./29.html">29</option>
        <option value="./30.html">30</option>
        <option value="./31.html">31</option>
        <option value="./32.html">32</option>
        <option value="./33.html">33</option>
        <option value="./34.html">34</option>
        <option value="./35.html">35</option>
        <option value="./36.html">36</option>
        <option value="./37.html">37</option>
        <option value="./38.html">38</option>
        <option value="./39.html">39</option>
        <option value="./40.html">40</option>
        <option value="./41.html">41</option>
        <option value="./42.html">42</option>
        <option value="./43.html">43</option>
        <option value="./44.html">44</option>
        <option value="./45.html">45</option>
        <option value="./46.html">46</option>
        <option value="./47.html">47</option>
        <option value="./48.html">48</option>
        <option value="./49.html">49</option>
        <option value="./50.html">50</option>
        <option value="./51.html">51</option>
        <option value="./52.html">52</option>
        <option value="./53.html">53</option>
        <option value="./54.html">54</option>
        <option value="./55.html">55</option>
        <option value="./56.html">56</option>
        <option value="./57.html">57</option>
        <option value="./58.html">58</option>
        <option value="./59.html">59</option>
        <option value="./60.html">60</option>
        <option value="./61.html">61</option>
        <option value="./62.html">62</option>
        <option value="./63.html">63</option>
        <option value="./64.html">64</option>
        <option value="./65.html">65</option>
        <option value="./66.html">66</option>
        <option value="./67.html">67</option>
        <option value="./68.html">68</option>
        <option value="./69.html">69</option>
        <option value="./70.html">70</option>
        <option value="./71.html">71</option>
        <option value="./72.html">72</option>
        <option value="./73.html">73</option>
        <option value="./74.html">74</option>
        <option value="./75.html">75</option>
        <option value="./76.html">76</option>
        <option value="./77.html">77</option>
        <option value="./78.html">78</option>
        <option value="./79.html">79</option>
        <option value="./80.html">80</option>
        <option value="./81.html">81</option>
        <option value="./82.html">82</option>
        <option value="./83.html">83</option>
        <option value="./84.html">84</option>
        <option value="./85.html">85</option>
        <option value="./86.html">86</option>
        <option value="./87.html">87</option>
        <option value="./88.html">88</option>
        <option value="./89.html">89</option>
        <option value="./90.html">90</option>
        <option value="./91.html">91</option>
        <option value="./92.html">92</option>
        <option value="./93.html">93</option>
        <option value="./94.html">94</option>
        <option value="./95.html">95</option>
        <option value="./96.html">96</option>
        <option value="./97.html">97</option>
        <option value="./98.html">98</option>
        <option value="./99.html">99</option>
        <option value="./100.html">100</option>
        <option value="./101.html">101</option>
        <option value="./102.html">102</option>
        <option value="./103.html">103</option>
        <option value="./104.html">104</option>
        <option value="./105.html">105</option>
    `;
    sele.innerHTML += select_element;


    