let manga_info = [
  {
    "nome" : "Atsumori-kun no Oyome-san",
    "num_capitulo" : "70",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2018",
    "genero" : "Comedia Drama Romance Shoujo Slice-of-Life",
  },
  {
    "nome" : "Father, I Don't Want this Marriage! (Father, I Don't Want to Get Married!)",
    "num_capitulo" : "62",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2022",
    "genero" : "Acao Aventura Comedia Demonios Drama Familia Magia Manhwa Reencarnação Romance Shoujo",
  },
  {
    "nome" : "My Childhood Friend Became an Obsessive Male Lead",
    "num_capitulo" : "46",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Drama Fantasia Josei Romance",
  },
  {
    "nome" : "A Proprietária Bebê Está se Aposentando",
    "num_capitulo" : "120",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Fantasia Romance Shoujo",
  },
  {
    "nome" : "Isekai De Tochi O Katte Noujou O Tsukurou",
    "num_capitulo" : "31",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2019",
    "genero" : "Ação Aventura Comédia Ecchi Fantasia Harem Romance Shounen",
  },
  {
    "nome" : "Kekkon Yubiwa Monogatari",
    "num_capitulo" : "62",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2016",
    "genero" : "Ação Ecchi Fantasia Harem Magia Romance Seinen",
  },
  {
    "nome" : "Wojia Laopo Laizi Yiqian Nian Qian – My Wife Is From a Thousand Years Ago",
    "num_capitulo" : "23",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Drama Fantasia Romance Shounen Sobrenatural",
  },
  {
    "nome" : "Fuufu Ijou, Koibito Miman",
    "num_capitulo" : "65",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2020",
    "genero" : "Comédia Drama Escolar Romance Slice-of-Life",
  },
  {
    "nome" : "Pretendente Surpresa",
    "num_capitulo" : "124",
    "text_cap" : "Capitulos: ",
    "estado" : "Finalizado",
    "lancamento" : "2020",
    "genero" : "Comédia Drama Josei Romance Slice-of-Life",
  },
  {
    "nome" : "I’m Not a Demon",
    "num_capitulo" : "19",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2023",
    "genero" : "Ação Aventura Drama Fantasia Shounen",
  },
  {
    "nome" : "Quando a Filha Ilegítima do Conde se Casa",
    "num_capitulo" : "79",
    "text_cap" : "Capitulos: ",
    "estado" : "",
    "lancamento" : "2022",
    "genero" : "Comédia Drama Josei Romance Slice-of-Life",
  },
  {
    "nome" : "Adelaide",
    "num_capitulo" : "85",
    "text_cap" : "Capitulos:",
    "estado" : "Finalizado",
    "lancamento" : "2023",
    "genero" : "Fantasia Histórico Isekai Romance",
  },
  {
    "nome" : "I Confessed to the Boss",
    "num_capitulo" : "59",
    "text_cap" : "Capitulos:",
    "estado" : "",
    "lancamento" : "2021",
    "genero" : "Comedia Drama Josei Romance Shoujo",
  },
  {
    "nome" : "A protagonista feminina está tentando me tornar sua madrasta",
    "num_capitulo" : "41",
    "text_cap" : "Capitulos:",
    "estado" : "Finalizado",
    "lancamento" : "2021",
    "genero" : "Fantasia Histórico Josei Romance Shoujo",
  },
];




